<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Modelos lineales generalizados | Modelos lineales y aditivos en ecología</title>
  <meta name="description" content="Scripts del curso" />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Modelos lineales generalizados | Modelos lineales y aditivos en ecología" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Scripts del curso" />
  <meta name="github-repo" content="facuxpalacio/Curso_modelos_lineales_y_aditivos_en_ecologia_2022/bookdown_curso" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Modelos lineales generalizados | Modelos lineales y aditivos en ecología" />
  
  <meta name="twitter:description" content="Scripts del curso" />
  

<meta name="author" content="Facundo X. Palacio" />


<meta name="date" content="2022-05-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="GAM.html"/>
<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción a los modelos lineales<span></span></a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#definición-de-modelo-lineal"><i class="fa fa-check"></i><b>1.1</b> Definición de modelo lineal<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#correlación-lineal-simple"><i class="fa fa-check"></i><b>1.2</b> Correlación lineal simple<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#matrices-de-correlación"><i class="fa fa-check"></i><b>1.3</b> Matrices de correlación<span></span></a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#regresión-lineal-simple"><i class="fa fa-check"></i><b>1.4</b> Regresión lineal simple<span></span></a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#relación-entre-regresión-y-correlación"><i class="fa fa-check"></i><b>1.5</b> Relación entre regresión y correlación<span></span></a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#matrices-de-gráficos-de-dispersión"><i class="fa fa-check"></i><b>1.6</b> Matrices de gráficos de dispersión<span></span></a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#regresión-lineal-multiple"><i class="fa fa-check"></i><b>1.7</b> Regresión lineal multiple<span></span></a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#variables-categóricas-dummies"><i class="fa fa-check"></i><b>1.8</b> Variables categóricas (= <em>dummies</em>)<span></span></a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#test-de-t"><i class="fa fa-check"></i><b>1.9</b> Test de <em>t</em><span></span></a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#test-de-t-pareado"><i class="fa fa-check"></i><b>1.10</b> Test de <em>t</em> pareado<span></span></a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#análisis-de-la-varianza"><i class="fa fa-check"></i><b>1.11</b> Análisis de la varianza<span></span></a></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#supuestos"><i class="fa fa-check"></i><b>1.12</b> Supuestos<span></span></a><ul>
<li class="chapter" data-level="1.12.1" data-path="index.html"><a href="index.html#colinealidad"><i class="fa fa-check"></i><b>1.12.1</b> Colinealidad<span></span></a></li>
<li class="chapter" data-level="1.12.2" data-path="index.html"><a href="index.html#análisis-de-residuos"><i class="fa fa-check"></i><b>1.12.2</b> Análisis de residuos<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="index.html"><a href="index.html#transformaciones"><i class="fa fa-check"></i><b>1.13</b> Transformaciones<span></span></a></li>
<li class="chapter" data-level="1.14" data-path="index.html"><a href="index.html#actividades"><i class="fa fa-check"></i><b>1.14</b> Actividades<span></span></a><ul>
<li class="chapter" data-level="1.14.1" data-path="index.html"><a href="index.html#ejercicios-de-repaso"><i class="fa fa-check"></i><b>1.14.1</b> Ejercicios de repaso<span></span></a></li>
<li class="chapter" data-level="1.14.2" data-path="index.html"><a href="index.html#ejercicio-1.2"><i class="fa fa-check"></i><b>1.14.2</b> Ejercicio 1.2<span></span></a></li>
<li class="chapter" data-level="1.14.3" data-path="index.html"><a href="index.html#ejercicio-1.3"><i class="fa fa-check"></i><b>1.14.3</b> Ejercicio 1.3<span></span></a></li>
<li class="chapter" data-level="1.14.4" data-path="index.html"><a href="index.html#ejercicio-1.4"><i class="fa fa-check"></i><b>1.14.4</b> Ejercicio 1.4<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="GLM.html"><a href="GLM.html"><i class="fa fa-check"></i><b>2</b> Modelos lineales generalizados<span></span></a><ul>
<li class="chapter" data-level="2.1" data-path="GLM.html"><a href="GLM.html#datos-de-presencia-ausencia"><i class="fa fa-check"></i><b>2.1</b> Datos de presencia-ausencia<span></span></a><ul>
<li class="chapter" data-level="2.1.1" data-path="GLM.html"><a href="GLM.html#glm-binomial"><i class="fa fa-check"></i><b>2.1.1</b> GLM binomial<span></span></a></li>
<li class="chapter" data-level="2.1.2" data-path="GLM.html"><a href="GLM.html#diagnósticos"><i class="fa fa-check"></i><b>2.1.2</b> Diagnósticos<span></span></a></li>
<li class="chapter" data-level="2.1.3" data-path="GLM.html"><a href="GLM.html#bondad-del-ajuste"><i class="fa fa-check"></i><b>2.1.3</b> Bondad del ajuste<span></span></a></li>
<li class="chapter" data-level="2.1.4" data-path="GLM.html"><a href="GLM.html#gráfico-del-modelo"><i class="fa fa-check"></i><b>2.1.4</b> Gráfico del modelo<span></span></a></li>
<li class="chapter" data-level="2.1.5" data-path="GLM.html"><a href="GLM.html#interpretación-de-los-coeficientes"><i class="fa fa-check"></i><b>2.1.5</b> Interpretación de los coeficientes<span></span></a></li>
<li class="chapter" data-level="2.1.6" data-path="GLM.html"><a href="GLM.html#ecuación"><i class="fa fa-check"></i><b>2.1.6</b> Ecuación<span></span></a></li>
<li class="chapter" data-level="2.1.7" data-path="GLM.html"><a href="GLM.html#capacidad-predictiva"><i class="fa fa-check"></i><b>2.1.7</b> Capacidad predictiva<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="GLM.html"><a href="GLM.html#conteos-i"><i class="fa fa-check"></i><b>2.2</b> Conteos I<span></span></a><ul>
<li class="chapter" data-level="2.2.1" data-path="GLM.html"><a href="GLM.html#glms-poisson-y-quasi-poisson"><i class="fa fa-check"></i><b>2.2.1</b> GLMs Poisson y quasi-Poisson<span></span></a></li>
<li class="chapter" data-level="2.2.2" data-path="GLM.html"><a href="GLM.html#glm-binomial-negativo"><i class="fa fa-check"></i><b>2.2.2</b> GLM binomial negativo<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="GLM.html"><a href="GLM.html#modelo-lineal-general"><i class="fa fa-check"></i><b>2.3</b> Modelo lineal general<span></span></a></li>
<li class="chapter" data-level="2.4" data-path="GLM.html"><a href="GLM.html#glm-gamma"><i class="fa fa-check"></i><b>2.4</b> GLM Gamma<span></span></a></li>
<li class="chapter" data-level="2.5" data-path="GLM.html"><a href="GLM.html#actividades-1"><i class="fa fa-check"></i><b>2.5</b> Actividades<span></span></a><ul>
<li class="chapter" data-level="2.5.1" data-path="GLM.html"><a href="GLM.html#ejercicio-2.1"><i class="fa fa-check"></i><b>2.5.1</b> Ejercicio 2.1<span></span></a></li>
<li class="chapter" data-level="2.5.2" data-path="GLM.html"><a href="GLM.html#ejercicio-2.2"><i class="fa fa-check"></i><b>2.5.2</b> Ejercicio 2.2<span></span></a></li>
<li class="chapter" data-level="2.5.3" data-path="GLM.html"><a href="GLM.html#ejercicio-2.3"><i class="fa fa-check"></i><b>2.5.3</b> Ejercicio 2.3<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="GLM.html"><a href="GLM.html#conteos-ii"><i class="fa fa-check"></i><b>2.6</b> Conteos II<span></span></a><ul>
<li class="chapter" data-level="2.6.1" data-path="GLM.html"><a href="GLM.html#modelos-truncados-en-cero"><i class="fa fa-check"></i><b>2.6.1</b> Modelos truncados en cero<span></span></a></li>
<li class="chapter" data-level="2.6.2" data-path="GLM.html"><a href="GLM.html#modelos-inflados-en-ceros"><i class="fa fa-check"></i><b>2.6.2</b> Modelos inflados en ceros<span></span></a></li>
<li class="chapter" data-level="2.6.3" data-path="GLM.html"><a href="GLM.html#interpretación-y-gráficos-del-modelo-1"><i class="fa fa-check"></i><b>2.6.3</b> Interpretación y gráficos del modelo<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="GLM.html"><a href="GLM.html#inferencia-multimodelo"><i class="fa fa-check"></i><b>2.7</b> Inferencia multimodelo<span></span></a><ul>
<li class="chapter" data-level="2.7.1" data-path="GLM.html"><a href="GLM.html#selección-de-modelos"><i class="fa fa-check"></i><b>2.7.1</b> Selección de modelos<span></span></a></li>
<li class="chapter" data-level="2.7.2" data-path="GLM.html"><a href="GLM.html#promediado-de-modelos"><i class="fa fa-check"></i><b>2.7.2</b> Promediado de modelos<span></span></a></li>
<li class="chapter" data-level="2.7.3" data-path="GLM.html"><a href="GLM.html#gráfico-del-modelo-promedio"><i class="fa fa-check"></i><b>2.7.3</b> Gráfico del modelo promedio<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="GLM.html"><a href="GLM.html#actividades-2"><i class="fa fa-check"></i><b>2.8</b> Actividades<span></span></a><ul>
<li class="chapter" data-level="2.8.1" data-path="GLM.html"><a href="GLM.html#ejercicio-3.1"><i class="fa fa-check"></i><b>2.8.1</b> Ejercicio 3.1<span></span></a></li>
<li class="chapter" data-level="2.8.2" data-path="GLM.html"><a href="GLM.html#ejercicio-3.2"><i class="fa fa-check"></i><b>2.8.2</b> Ejercicio 3.2<span></span></a></li>
<li class="chapter" data-level="2.8.3" data-path="GLM.html"><a href="GLM.html#ejercicio-3.3"><i class="fa fa-check"></i><b>2.8.3</b> Ejercicio 3.3<span></span></a></li>
<li class="chapter" data-level="2.8.4" data-path="GLM.html"><a href="GLM.html#ejercicio-3.4"><i class="fa fa-check"></i><b>2.8.4</b> Ejercicio 3.4<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="GAM.html"><a href="GAM.html"><i class="fa fa-check"></i><b>3</b> Modelos no lineales<span></span></a><ul>
<li class="chapter" data-level="3.1" data-path="GAM.html"><a href="GAM.html#regresión-no-paramétrica"><i class="fa fa-check"></i><b>3.1</b> Regresión no paramétrica<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="GAM.html"><a href="GAM.html#regresión-polinómica"><i class="fa fa-check"></i><b>3.2</b> Regresión polinómica<span></span></a></li>
<li class="chapter" data-level="3.3" data-path="GAM.html"><a href="GAM.html#funciones-a-trozos"><i class="fa fa-check"></i><b>3.3</b> Funciones a trozos<span></span></a></li>
<li class="chapter" data-level="3.4" data-path="GAM.html"><a href="GAM.html#splines-de-regresión"><i class="fa fa-check"></i><b>3.4</b> Splines de regresión<span></span></a><ul>
<li class="chapter" data-level="3.4.1" data-path="GAM.html"><a href="GAM.html#polinomios-a-trozos"><i class="fa fa-check"></i><b>3.4.1</b> Polinomios a trozos<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="GAM.html"><a href="GAM.html#modelos-aditivos-generalizados"><i class="fa fa-check"></i><b>3.5</b> Modelos aditivos generalizados<span></span></a><ul>
<li class="chapter" data-level="3.5.1" data-path="GAM.html"><a href="GAM.html#gam-con-otras-distribuciones-e-interacciones"><i class="fa fa-check"></i><b>3.5.1</b> GAM con otras distribuciones e interacciones<span></span></a></li>
<li class="chapter" data-level="3.5.2" data-path="GAM.html"><a href="GAM.html#comparación-de-modelos"><i class="fa fa-check"></i><b>3.5.2</b> Comparación de modelos<span></span></a></li>
<li class="chapter" data-level="3.5.3" data-path="GAM.html"><a href="GAM.html#validación-2"><i class="fa fa-check"></i><b>3.5.3</b> Validación<span></span></a></li>
<li class="chapter" data-level="3.5.4" data-path="GAM.html"><a href="GAM.html#modelo-con-variables-continuas-efectos-principales-interacciones"><i class="fa fa-check"></i><b>3.5.4</b> Modelo con variables continuas (efectos principales + interacciones)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="GAM.html"><a href="GAM.html#actividades-3"><i class="fa fa-check"></i><b>3.6</b> Actividades<span></span></a><ul>
<li class="chapter" data-level="3.6.1" data-path="GAM.html"><a href="GAM.html#ejercicio-4.1"><i class="fa fa-check"></i><b>3.6.1</b> Ejercicio 4.1<span></span></a></li>
<li class="chapter" data-level="3.6.2" data-path="GAM.html"><a href="GAM.html#ejercicio-4.2"><i class="fa fa-check"></i><b>3.6.2</b> Ejercicio 4.2<span></span></a></li>
<li class="chapter" data-level="3.6.3" data-path="GAM.html"><a href="GAM.html#ejercicio-4.3"><i class="fa fa-check"></i><b>3.6.3</b> Ejercicio 4.3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mixtos.html"><a href="mixtos.html"><i class="fa fa-check"></i><b>4</b> Modelos mixtos<span></span></a><ul>
<li class="chapter" data-level="4.1" data-path="mixtos.html"><a href="mixtos.html#dependencia-temporal"><i class="fa fa-check"></i><b>4.1</b> Dependencia temporal<span></span></a></li>
<li class="chapter" data-level="4.2" data-path="mixtos.html"><a href="mixtos.html#dependencia-espacial"><i class="fa fa-check"></i><b>4.2</b> Dependencia espacial<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="mixtos.html"><a href="mixtos.html#introducción-a-los-modelos-mixtos"><i class="fa fa-check"></i><b>4.3</b> Introducción a los modelos mixtos<span></span></a></li>
<li class="chapter" data-level="4.4" data-path="mixtos.html"><a href="mixtos.html#un-caso-especial"><i class="fa fa-check"></i><b>4.4</b> Un caso especial<span></span></a></li>
<li class="chapter" data-level="4.5" data-path="mixtos.html"><a href="mixtos.html#modelos-lineales-generalizados-mixtos"><i class="fa fa-check"></i><b>4.5</b> Modelos lineales generalizados mixtos<span></span></a></li>
<li class="chapter" data-level="4.6" data-path="mixtos.html"><a href="mixtos.html#modelos-mixtos-con-estructura-espacial"><i class="fa fa-check"></i><b>4.6</b> Modelos mixtos con estructura espacial<span></span></a></li>
<li class="chapter" data-level="4.7" data-path="mixtos.html"><a href="mixtos.html#modelos-mixtos-con-filogenia"><i class="fa fa-check"></i><b>4.7</b> Modelos mixtos con filogenia<span></span></a></li>
<li class="chapter" data-level="4.8" data-path="mixtos.html"><a href="mixtos.html#modelos-aditivos-generalizados-mixtos"><i class="fa fa-check"></i><b>4.8</b> Modelos aditivos generalizados mixtos<span></span></a><ul>
<li class="chapter" data-level="4.8.1" data-path="mixtos.html"><a href="mixtos.html#ajuste-de-modelos"><i class="fa fa-check"></i><b>4.8.1</b> Ajuste de modelos<span></span></a></li>
<li class="chapter" data-level="4.8.2" data-path="mixtos.html"><a href="mixtos.html#gráficos"><i class="fa fa-check"></i><b>4.8.2</b> Gráficos<span></span></a></li>
<li class="chapter" data-level="4.8.3" data-path="mixtos.html"><a href="mixtos.html#autocorrelación-temporal"><i class="fa fa-check"></i><b>4.8.3</b> Autocorrelación temporal<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="mixtos.html"><a href="mixtos.html#actividades-4"><i class="fa fa-check"></i><b>4.9</b> Actividades<span></span></a><ul>
<li class="chapter" data-level="4.9.1" data-path="mixtos.html"><a href="mixtos.html#ejercicio-5.4"><i class="fa fa-check"></i><b>4.9.1</b> Ejercicio 5.4<span></span></a></li>
<li class="chapter" data-level="4.9.2" data-path="mixtos.html"><a href="mixtos.html#ejercicio-5.5"><i class="fa fa-check"></i><b>4.9.2</b> Ejercicio 5.5<span></span></a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos lineales y aditivos en ecología</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="GLM" class="section level1 hasAnchor">
<h1><span class="header-section-number">2</span> Modelos lineales generalizados<a href="GLM.html#GLM" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="datos-de-presencia-ausencia" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.1</span> Datos de presencia-ausencia<a href="GLM.html#datos-de-presencia-ausencia" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cabral et al. (2007) estudiaron la distribución de platijas (<em>Solea solea</em>) en el estuario Tagus, Portugal (<code>Solea.txt</code>). Se desea saber qué factores (temperatura, transparencia, salinidad) están relacionados con la presencia esta especie.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="GLM.html#cb107-1"></a><span class="co"># Analisis exploratorio</span></span>
<span id="cb107-2"><a href="GLM.html#cb107-2"></a>datos &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;Solea.txt&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)</span>
<span id="cb107-3"><a href="GLM.html#cb107-3"></a><span class="kw">str</span>(datos)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    65 obs. of  13 variables:
##  $ Sample       : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ season       : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ month        : int  5 5 5 5 5 5 5 5 5 5 ...
##  $ Area         : int  2 2 2 4 4 4 3 3 3 1 ...
##  $ depth        : num  3 2.6 2.6 2.1 3.2 3.5 1.6 1.7 1.8 4.5 ...
##  $ temperature  : int  20 18 19 20 20 20 19 17 19 21 ...
##  $ salinity     : int  30 29 30 29 30 32 29 28 29 12 ...
##  $ transparency : int  15 15 15 15 15 7 15 10 10 35 ...
##  $ gravel       : num  3.74 1.94 2.88 11.06 9.87 ...
##  $ large_sand   : num  13.15 4.99 8.98 11.96 28.6 ...
##  $ med_fine_sand: num  11.93 5.43 16.85 21.95 19.49 ...
##  $ mud          : num  71.2 87.6 71.3 55 42 ...
##  $ Solea_solea  : int  0 0 1 0 0 0 1 1 0 1 ...</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="GLM.html#cb109-1"></a><span class="kw">hist</span>(datos<span class="op">$</span>Solea_solea)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo1-1.png" width="672" /></p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="GLM.html#cb110-1"></a><span class="kw">table</span>(datos<span class="op">$</span>Solea_solea)</span></code></pre></div>
<pre><code>## 
##  0  1 
## 39 26</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="GLM.html#cb112-1"></a><span class="kw">pairs</span>(datos[, <span class="dv">4</span><span class="op">:</span><span class="dv">12</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/explo1-2.png" width="672" /></p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="GLM.html#cb113-1"></a><span class="kw">round</span>(<span class="kw">cor</span>(datos[, <span class="dv">4</span><span class="op">:</span><span class="dv">12</span>]), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                Area depth temperature salinity transparency gravel large_sand
## Area           1.00 -0.55       -0.18     0.76        -0.56   0.44      -0.44
## depth         -0.55  1.00        0.14    -0.66         0.57  -0.24       0.31
## temperature   -0.18  0.14        1.00    -0.35         0.54  -0.16       0.12
## salinity       0.76 -0.66       -0.35     1.00        -0.66   0.38      -0.54
## transparency  -0.56  0.57        0.54    -0.66         1.00  -0.25       0.37
## gravel         0.44 -0.24       -0.16     0.38        -0.25   1.00       0.01
## large_sand    -0.44  0.31        0.12    -0.54         0.37   0.01       1.00
## med_fine_sand -0.69  0.67        0.25    -0.80         0.69  -0.32       0.56
## mud            0.49 -0.47       -0.16     0.63        -0.52  -0.19      -0.87
##               med_fine_sand   mud
## Area                  -0.69  0.49
## depth                  0.67 -0.47
## temperature            0.25 -0.16
## salinity              -0.80  0.63
## transparency           0.69 -0.52
## gravel                -0.32 -0.19
## large_sand             0.56 -0.87
## med_fine_sand          1.00 -0.78
## mud                   -0.78  1.00</code></pre>
<div id="glm-binomial" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.1.1</span> GLM binomial<a href="GLM.html#glm-binomial" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="GLM.html#cb115-1"></a>m.bin &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>temperature <span class="op">+</span><span class="st"> </span>transparency <span class="op">+</span><span class="st"> </span>salinity, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb115-2"><a href="GLM.html#cb115-2"></a><span class="kw">summary</span>(m.bin)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Solea_solea ~ temperature + transparency + salinity, 
##     family = binomial, data = datos)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2170  -0.7607  -0.6364   0.7219   1.8447  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   5.221629   3.524358   1.482  0.13845   
## temperature  -0.100542   0.148829  -0.676  0.49932   
## transparency -0.001162   0.025347  -0.046  0.96343   
## salinity     -0.142652   0.049986  -2.854  0.00432 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 87.492  on 64  degrees of freedom
## Residual deviance: 67.973  on 61  degrees of freedom
## AIC: 75.973
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div id="diagnósticos" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.1.2</span> Diagnósticos<a href="GLM.html#diagnósticos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="GLM.html#cb117-1"></a><span class="kw">plot</span>(m.bin)</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20glm%20binomial-1.png" width="672" /><img src="_main_files/figure-html/validacion%20glm%20binomial-2.png" width="672" /><img src="_main_files/figure-html/validacion%20glm%20binomial-3.png" width="672" /><img src="_main_files/figure-html/validacion%20glm%20binomial-4.png" width="672" /></p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="GLM.html#cb118-1"></a><span class="kw">library</span>(DHARMa)</span></code></pre></div>
<pre><code>## Warning: package &#39;DHARMa&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;lme4&#39;:
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car</code></pre>
<pre><code>## This is DHARMa 0.4.5. For overview type &#39;?DHARMa&#39;. For recent changes, type news(package = &#39;DHARMa&#39;)</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="GLM.html#cb122-1"></a><span class="kw">plot</span>(<span class="kw">simulateResiduals</span>(<span class="dt">fittedModel =</span> m.bin))</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20glm%20binomial-5.png" width="672" /></p>
</div>
<div id="bondad-del-ajuste" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.1.3</span> Bondad del ajuste<a href="GLM.html#bondad-del-ajuste" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="GLM.html#cb123-1"></a><span class="kw">summary</span>(m.bin)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Solea_solea ~ temperature + transparency + salinity, 
##     family = binomial, data = datos)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2170  -0.7607  -0.6364   0.7219   1.8447  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   5.221629   3.524358   1.482  0.13845   
## temperature  -0.100542   0.148829  -0.676  0.49932   
## transparency -0.001162   0.025347  -0.046  0.96343   
## salinity     -0.142652   0.049986  -2.854  0.00432 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 87.492  on 64  degrees of freedom
## Residual deviance: 67.973  on 61  degrees of freedom
## AIC: 75.973
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="GLM.html#cb125-1"></a><span class="co"># Pseudo-R2</span></span>
<span id="cb125-2"><a href="GLM.html#cb125-2"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(m.bin<span class="op">$</span>dev<span class="op">/</span>m.bin<span class="op">$</span>null)</span></code></pre></div>
<pre><code>## [1] 0.2230856</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="GLM.html#cb127-1"></a><span class="kw">library</span>(performance)</span></code></pre></div>
<pre><code>## Warning: package &#39;performance&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="GLM.html#cb129-1"></a><span class="co"># Coeficiente de determinación de Tjur</span></span>
<span id="cb129-2"><a href="GLM.html#cb129-2"></a><span class="kw">r2_tjur</span>(m.bin) </span></code></pre></div>
<pre><code>## Tjur&#39;s R2 
## 0.2840808</code></pre>
</div>
<div id="gráfico-del-modelo" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.1.4</span> Gráfico del modelo<a href="GLM.html#gráfico-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="GLM.html#cb131-1"></a><span class="kw">library</span>(visreg)</span>
<span id="cb131-2"><a href="GLM.html#cb131-2"></a><span class="kw">visreg</span>(<span class="dt">fit =</span> m.bin, <span class="dt">xvar =</span> <span class="st">&quot;salinity&quot;</span>, <span class="dt">scale =</span> <span class="st">&quot;response&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb131-3"><a href="GLM.html#cb131-3"></a>       <span class="dt">xlab =</span> <span class="st">&quot;Salinidad&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Probabilidad de presencia&quot;</span>) </span>
<span id="cb131-4"><a href="GLM.html#cb131-4"></a><span class="kw">points</span>(datos<span class="op">$</span>salinity, datos<span class="op">$</span>Solea_solea)</span></code></pre></div>
<p><img src="_main_files/figure-html/grafico%20binomial-1.png" width="672" /></p>
</div>
<div id="interpretación-de-los-coeficientes" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.1.5</span> Interpretación de los coeficientes<a href="GLM.html#interpretación-de-los-coeficientes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="GLM.html#cb132-1"></a><span class="kw">exp</span>(m.bin<span class="op">$</span>coeff[<span class="dv">2</span>]) <span class="co"># Razon de odds</span></span></code></pre></div>
<pre><code>## temperature 
##   0.9043472</code></pre>
<p>Esto quiere decir que, por unidad de salinidad, la relacion <span class="math inline">\(\frac{P(presencia)}{P(ausencia)}\)</span> (odd) disminuye en 0.90 unidades</p>
</div>
<div id="ecuación" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.1.6</span> Ecuación<a href="GLM.html#ecuación" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="GLM.html#cb134-1"></a><span class="kw">library</span>(equatiomatic)</span></code></pre></div>
<pre><code>## Warning: package &#39;equatiomatic&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="GLM.html#cb136-1"></a><span class="kw">extract_eq</span>(m.bin, <span class="dt">use_coefs =</span> <span class="ot">TRUE</span>, <span class="dt">fix_signs =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><span class="math display">\[
\log\left[ \frac { \widehat{P( \operatorname{Solea\_solea} = \operatorname{1} )} }{ 1 - \widehat{P( \operatorname{Solea\_solea} = \operatorname{1} )} } \right] = 5.22 - 0.1(\operatorname{temperature}) + 0(\operatorname{transparency}) - 0.14(\operatorname{salinity})
\]</span></p>
</div>
<div id="capacidad-predictiva" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.1.7</span> Capacidad predictiva<a href="GLM.html#capacidad-predictiva" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="GLM.html#cb137-1"></a><span class="co"># Matriz de confusión</span></span>
<span id="cb137-2"><a href="GLM.html#cb137-2"></a>obs &lt;-<span class="st"> </span>datos<span class="op">$</span>Solea_solea</span>
<span id="cb137-3"><a href="GLM.html#cb137-3"></a>pred &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">predict</span>(m.bin, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)<span class="op">&gt;</span><span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb137-4"><a href="GLM.html#cb137-4"></a>matriz.conf &lt;-<span class="st"> </span><span class="kw">table</span>(obs, pred) </span>
<span id="cb137-5"><a href="GLM.html#cb137-5"></a>matriz.conf</span></code></pre></div>
<pre><code>##    pred
## obs  0  1
##   0 34  5
##   1 11 15</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="GLM.html#cb139-1"></a><span class="co"># Porcentajes de clasificación</span></span>
<span id="cb139-2"><a href="GLM.html#cb139-2"></a>matriz.conf<span class="op">/</span><span class="kw">rowSums</span>(matriz.conf)</span></code></pre></div>
<pre><code>##    pred
## obs         0         1
##   0 0.8717949 0.1282051
##   1 0.4230769 0.5769231</code></pre>
</div>
</div>
<div id="conteos-i" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.2</span> Conteos I<a href="GLM.html#conteos-i" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Gotelli &amp; Ellison (2002) analizaron los determinantes biogeográficos de la riqueza de hormigas (<code>Srich</code>) a escala regional (<code>hormigas.txt</code>). Para esto se describieron el tipo de hábitat (<code>Habitat</code>), la latitud (<code>Latitude</code>) y la altitud (<code>Elevation</code>).</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="GLM.html#cb141-1"></a><span class="co"># Análisis exploratorio</span></span>
<span id="cb141-2"><a href="GLM.html#cb141-2"></a>h &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;hormigas.txt&quot;</span>, <span class="dt">header =</span> T) </span>
<span id="cb141-3"><a href="GLM.html#cb141-3"></a><span class="kw">str</span>(h)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    44 obs. of  5 variables:
##  $ Site     : chr  &quot;TPB&quot; &quot;HBC&quot; &quot;CKB&quot; &quot;SKP&quot; ...
##  $ Srich    : int  6 16 18 17 9 15 7 12 14 9 ...
##  $ Habitat  : chr  &quot;Forest&quot; &quot;Forest&quot; &quot;Forest&quot; &quot;Forest&quot; ...
##  $ Latitude : num  42 42 42 42 42 ...
##  $ Elevation: int  389 8 152 1 210 78 47 491 121 95 ...</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="GLM.html#cb143-1"></a>h<span class="op">$</span>Habitat &lt;-<span class="st"> </span><span class="kw">as.factor</span>(h<span class="op">$</span>Habitat)</span>
<span id="cb143-2"><a href="GLM.html#cb143-2"></a><span class="kw">pairs</span>(h[, <span class="dv">2</span><span class="op">:</span><span class="dv">5</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/explo2-1.png" width="672" /></p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="GLM.html#cb144-1"></a><span class="kw">round</span>(<span class="kw">cor</span>(h[, <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span><span class="op">:</span><span class="dv">5</span>)]), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##           Srich Latitude Elevation
## Srich      1.00    -0.44     -0.38
## Latitude  -0.44     1.00      0.18
## Elevation -0.38     0.18      1.00</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="GLM.html#cb146-1"></a><span class="kw">plot</span>(<span class="kw">table</span>(h<span class="op">$</span>Srich), <span class="dt">xlab =</span> <span class="st">&quot;Número de especies&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Frecuencia&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo2-2.png" width="672" /></p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="GLM.html#cb147-1"></a><span class="kw">hist</span>(h<span class="op">$</span>Srich, <span class="dt">xlab =</span> <span class="st">&quot;Número de especies&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Frecuencia relativa&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>, <span class="dt">freq =</span> <span class="ot">FALSE</span>)</span>
<span id="cb147-2"><a href="GLM.html#cb147-2"></a></span>
<span id="cb147-3"><a href="GLM.html#cb147-3"></a><span class="co"># Ajuste de distribución a los datos</span></span>
<span id="cb147-4"><a href="GLM.html#cb147-4"></a>sim.pois &lt;-<span class="st"> </span><span class="kw">dpois</span>(<span class="dt">x =</span> <span class="dv">0</span><span class="op">:</span><span class="kw">max</span>(h<span class="op">$</span>Srich), <span class="dt">lambda =</span> <span class="kw">mean</span>(h<span class="op">$</span>Srich))</span>
<span id="cb147-5"><a href="GLM.html#cb147-5"></a><span class="kw">lines</span>(<span class="dt">x =</span> <span class="dv">0</span><span class="op">:</span><span class="kw">max</span>(h<span class="op">$</span>Srich), <span class="dt">y =</span> sim.pois, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo2-3.png" width="672" /></p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="GLM.html#cb148-1"></a><span class="kw">var</span>(h<span class="op">$</span>Srich)<span class="op">/</span><span class="kw">mean</span>(h<span class="op">$</span>Srich)</span></code></pre></div>
<pre><code>## [1] 2.566343</code></pre>
<div id="glms-poisson-y-quasi-poisson" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.2.1</span> GLMs Poisson y quasi-Poisson<a href="GLM.html#glms-poisson-y-quasi-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="glm-poisson" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.1.1</span> GLM Poisson<a href="GLM.html#glm-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="GLM.html#cb150-1"></a>m.pois &lt;-<span class="st"> </span><span class="kw">glm</span>(Srich <span class="op">~</span><span class="st"> </span>Latitude <span class="op">+</span><span class="st"> </span>Elevation <span class="op">+</span><span class="st"> </span>Habitat, <span class="dt">family =</span> poisson, <span class="dt">data =</span> h)</span>
<span id="cb150-2"><a href="GLM.html#cb150-2"></a><span class="kw">summary</span>(m.pois)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Srich ~ Latitude + Elevation + Habitat, family = poisson, 
##     data = h)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.20939  -0.72643  -0.05933   0.51571   2.60147  
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   11.9368121  2.6214970   4.553 5.28e-06 ***
## Latitude      -0.2357930  0.0616638  -3.824 0.000131 ***
## Elevation     -0.0011411  0.0003749  -3.044 0.002337 ** 
## HabitatForest  0.6354389  0.1195664   5.315 1.07e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 102.76  on 43  degrees of freedom
## Residual deviance:  40.69  on 40  degrees of freedom
## AIC: 209.04
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div id="glm-quasi-poisson" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.1.2</span> GLM quasi-Poisson<a href="GLM.html#glm-quasi-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="GLM.html#cb152-1"></a>m.qpois &lt;-<span class="st"> </span><span class="kw">glm</span>(Srich <span class="op">~</span><span class="st"> </span>Latitude <span class="op">+</span><span class="st"> </span>Elevation <span class="op">+</span><span class="st"> </span>Habitat, <span class="dt">family =</span> quasipoisson, <span class="dt">data =</span> h)</span>
<span id="cb152-2"><a href="GLM.html#cb152-2"></a><span class="kw">summary</span>(m.qpois)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Srich ~ Latitude + Elevation + Habitat, family = quasipoisson, 
##     data = h)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.20939  -0.72643  -0.05933   0.51571   2.60147  
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   11.9368121  2.6594025   4.489 5.94e-05 ***
## Latitude      -0.2357930  0.0625554  -3.769 0.000529 ***
## Elevation     -0.0011411  0.0003803  -3.000 0.004626 ** 
## HabitatForest  0.6354389  0.1212952   5.239 5.52e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 1.029128)
## 
##     Null deviance: 102.76  on 43  degrees of freedom
## Residual deviance:  40.69  on 40  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="GLM.html#cb154-1"></a><span class="co"># Parámetro de sobredispersión</span></span>
<span id="cb154-2"><a href="GLM.html#cb154-2"></a>resid &lt;-<span class="st"> </span><span class="kw">residuals</span>(m.qpois, <span class="dt">type =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb154-3"><a href="GLM.html#cb154-3"></a>nparam &lt;-<span class="st"> </span><span class="kw">length</span>(m.qpois<span class="op">$</span>coeff)</span>
<span id="cb154-4"><a href="GLM.html#cb154-4"></a>ndatos &lt;-<span class="st"> </span><span class="kw">nrow</span>(h)</span>
<span id="cb154-5"><a href="GLM.html#cb154-5"></a>disp.param &lt;-<span class="st"> </span><span class="kw">sum</span>(resid<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>(ndatos <span class="op">-</span><span class="st"> </span>nparam)</span>
<span id="cb154-6"><a href="GLM.html#cb154-6"></a>disp.param</span></code></pre></div>
<pre><code>## [1] 1.029116</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="GLM.html#cb156-1"></a>m.qpois.null &lt;-<span class="st"> </span><span class="kw">glm</span>(Srich <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">family =</span> quasipoisson, <span class="dt">data =</span> h)</span>
<span id="cb156-2"><a href="GLM.html#cb156-2"></a><span class="kw">summary</span>(m.qpois.null)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Srich ~ 1, family = quasipoisson, data = h)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2409  -1.2420  -0.3959   0.4492   3.4539  
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.94915    0.09113   21.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 2.566343)
## 
##     Null deviance: 102.76  on 43  degrees of freedom
## Residual deviance: 102.76  on 43  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="GLM.html#cb158-1"></a><span class="kw">library</span>(DHARMa)</span>
<span id="cb158-2"><a href="GLM.html#cb158-2"></a><span class="kw">testDispersion</span>(m.pois)</span></code></pre></div>
<p><img src="_main_files/figure-html/glm%20quasipoisson-1.png" width="672" /></p>
<pre><code>## 
##  DHARMa nonparametric dispersion test via sd of residuals fitted vs.
##  simulated
## 
## data:  simulationOutput
## dispersion = 1.0136, p-value = 0.92
## alternative hypothesis: two.sided</code></pre>
</div>
<div id="diagnósticos-1" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.1.3</span> Diagnósticos<a href="GLM.html#diagnósticos-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="GLM.html#cb160-1"></a>residP &lt;-<span class="st"> </span><span class="kw">resid</span>(m.qpois, <span class="dt">type =</span> <span class="st">&quot;pearson&quot;</span>)  <span class="co"># residuos de Pearson </span></span>
<span id="cb160-2"><a href="GLM.html#cb160-2"></a>residD &lt;-<span class="st"> </span><span class="kw">resid</span>(m.qpois, <span class="dt">type =</span> <span class="st">&quot;deviance&quot;</span>) <span class="co"># residuos de devianza </span></span>
<span id="cb160-3"><a href="GLM.html#cb160-3"></a>pred &lt;-<span class="st"> </span><span class="kw">predict</span>(m.qpois, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="co"># valores predichos </span></span>
<span id="cb160-4"><a href="GLM.html#cb160-4"></a><span class="kw">plot</span>(pred, residP) </span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20glm%20poisson-1.png" width="672" /></p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="GLM.html#cb161-1"></a><span class="kw">plot</span>(pred, residD)</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20glm%20poisson-2.png" width="672" /></p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="GLM.html#cb162-1"></a><span class="kw">plot</span>(<span class="kw">simulateResiduals</span>(<span class="dt">fittedModel =</span> m.pois))</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20glm%20poisson-3.png" width="672" /></p>
</div>
<div id="bondad-del-ajuste-1" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.1.4</span> Bondad del ajuste<a href="GLM.html#bondad-del-ajuste-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="GLM.html#cb163-1"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(m.qpois<span class="op">$</span>dev<span class="op">/</span>m.qpois<span class="op">$</span>null) <span class="co"># Pseudo-R2</span></span></code></pre></div>
<pre><code>## [1] 0.6040372</code></pre>
</div>
<div id="ecuación-1" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.1.5</span> Ecuación<a href="GLM.html#ecuación-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="GLM.html#cb165-1"></a><span class="kw">library</span>(equatiomatic)</span>
<span id="cb165-2"><a href="GLM.html#cb165-2"></a><span class="kw">extract_eq</span>(m.qpois, <span class="dt">use_coefs =</span> <span class="ot">TRUE</span>, <span class="dt">fix_signs =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><span class="math display">\[
\log ({ \widehat{E( \operatorname{Srich} )} })  = 11.94 - 0.24(\operatorname{Latitude}) + 0(\operatorname{Elevation}) + 0.64(\operatorname{Habitat}_{\operatorname{Forest}})
\]</span></p>
</div>
<div id="gráfico-del-modelo-1" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.1.6</span> Gráfico del modelo<a href="GLM.html#gráfico-del-modelo-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="GLM.html#cb166-1"></a><span class="kw">library</span>(visreg)</span>
<span id="cb166-2"><a href="GLM.html#cb166-2"></a><span class="kw">visreg</span>(<span class="dt">fit =</span> m.qpois, <span class="dt">xvar =</span> <span class="st">&quot;Latitude&quot;</span>, <span class="dt">by =</span> <span class="st">&quot;Habitat&quot;</span>, <span class="dt">overlay =</span> <span class="ot">TRUE</span>, </span>
<span id="cb166-3"><a href="GLM.html#cb166-3"></a>       <span class="dt">scale =</span> <span class="st">&quot;response&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;Latitud&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Número de especies&quot;</span>,</span>
<span id="cb166-4"><a href="GLM.html#cb166-4"></a>       <span class="dt">type =</span> <span class="st">&quot;conditional&quot;</span>, <span class="dt">cond =</span> <span class="kw">list</span>(<span class="dt">Latitude =</span> <span class="kw">mean</span>(h<span class="op">$</span>Latitude), <span class="dt">Elevation =</span> <span class="kw">mean</span>(h<span class="op">$</span>Elevation))) </span>
<span id="cb166-5"><a href="GLM.html#cb166-5"></a>bg &lt;-<span class="st"> </span>h[h<span class="op">$</span>Habitat <span class="op">==</span><span class="st"> &quot;Bog&quot;</span>, ] </span>
<span id="cb166-6"><a href="GLM.html#cb166-6"></a>ft &lt;-<span class="st"> </span>h[h<span class="op">$</span>Habitat <span class="op">==</span><span class="st"> &quot;Forest&quot;</span>, ] </span>
<span id="cb166-7"><a href="GLM.html#cb166-7"></a><span class="kw">points</span>(bg<span class="op">$</span>Latitude, bg<span class="op">$</span>Srich, <span class="dt">pch=</span><span class="dv">19</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>) </span>
<span id="cb166-8"><a href="GLM.html#cb166-8"></a><span class="kw">points</span>(ft<span class="op">$</span>Latitude, ft<span class="op">$</span>Srich, <span class="dt">pch=</span><span class="dv">19</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/grafico%20glm%20poisson-1.png" width="672" /></p>
</div>
</div>
<div id="glm-binomial-negativo" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.2.2</span> GLM binomial negativo<a href="GLM.html#glm-binomial-negativo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Leong et al. (2014) estudiaron el efecto del paisaje (urbano, agrícola y natural) sobre el número de interacciones de polinizadores nativos en <span class="math inline">\(Centaurea solstitialis\)</span> (Asteraceae). Se quiere evaluar si existen diferencias en el número de interacciones (<code>total</code>) entre los 3 tipos de ambientes (<code>type</code>) teniendo en cuenta la temperatura (<code>temp</code>) y la velocidad del viento (<code>wind</code>).</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="GLM.html#cb167-1"></a><span class="co"># Análisis exploratorio</span></span>
<span id="cb167-2"><a href="GLM.html#cb167-2"></a>pol &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;bees_data.txt&quot;</span>, <span class="dt">header =</span> T) </span>
<span id="cb167-3"><a href="GLM.html#cb167-3"></a><span class="kw">str</span>(pol)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    36 obs. of  34 variables:
##  $ locality    : chr  &quot;arabian&quot; &quot;arabian&quot; &quot;arabian&quot; &quot;bdm_f&quot; ...
##  $ type        : chr  &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;n&quot; ...
##  $ lat         : num  37.9 37.9 37.9 38 38 ...
##  $ long        : num  -122 -122 -122 -122 -122 ...
##  $ water       : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ urban       : int  18900 18900 18900 37800 37800 37800 4500 4500 4500 198000 ...
##  $ agr         : int  252000 252000 252000 0 0 0 16200 16200 16200 558000 ...
##  $ natural     : int  513900 513900 513900 747900 747900 747900 765000 765000 765000 32400 ...
##  $ bare        : int  1800 1800 1800 0 0 0 0 0 0 0 ...
##  $ bloom.cat   : int  3 3 3 3 3 3 4 4 4 4 ...
##  $ time        : chr  &quot;am&quot; &quot;mid&quot; &quot;pm&quot; &quot;am&quot; ...
##  $ wind        : num  2.7 1.35 0.8 2.3 3.75 3.7 2.4 2.15 2.5 0.85 ...
##  $ temp        : num  80.9 94.3 91.1 86.1 87.4 ...
##  $ hb          : int  70 44 24 34 24 27 40 29 14 88 ...
##  $ bumble      : int  0 0 0 1 0 4 0 0 0 0 ...
##  $ carpenter   : int  0 0 0 0 0 1 0 0 0 0 ...
##  $ hlb         : int  2 0 0 7 2 0 9 2 0 1 ...
##  $ svastra     : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ agtex       : int  4 1 0 0 0 0 0 0 0 0 ...
##  $ ssb.med     : int  0 0 0 0 0 0 1 0 0 1 ...
##  $ ssb.small   : int  0 0 1 4 0 4 1 3 2 9 ...
##  $ sdb.round   : int  1 0 6 1 1 1 2 3 4 2 ...
##  $ sdb.shield  : int  3 2 2 0 2 0 0 0 0 0 ...
##  $ shbb.large  : int  0 0 0 0 0 0 0 0 0 2 ...
##  $ shbb.med    : int  0 1 0 4 0 0 8 5 5 2 ...
##  $ shbb.small  : int  1 3 0 0 0 0 1 1 1 0 ...
##  $ anthidium   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ cuckoo      : int  0 0 0 0 0 0 1 0 0 0 ...
##  $ total.native: int  11 7 9 17 5 10 23 14 12 17 ...
##  $ total       : int  81 51 33 51 29 37 63 43 26 105 ...
##  $ min         : int  90 90 90 90 90 90 90 90 90 90 ...
##  $ num.group   : int  6 5 4 6 4 5 8 6 5 7 ...
##  $ shannon     : num  0.597 0.575 0.817 1.096 0.642 ...
##  $ even        : num  0.333 0.357 0.59 0.612 0.463 ...</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="GLM.html#cb169-1"></a>pol<span class="op">$</span>habitat &lt;-<span class="st"> </span><span class="kw">factor</span>(pol<span class="op">$</span>type, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;n&quot;</span>, <span class="st">&quot;a&quot;</span>, <span class="st">&quot;u&quot;</span>))</span>
<span id="cb169-2"><a href="GLM.html#cb169-2"></a><span class="kw">pairs</span>(pol[, <span class="kw">c</span>(<span class="st">&quot;habitat&quot;</span>, <span class="st">&quot;temp&quot;</span>, <span class="st">&quot;wind&quot;</span>, <span class="st">&quot;total&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/explo3-1.png" width="672" /></p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="GLM.html#cb170-1"></a><span class="kw">boxplot</span>(pol<span class="op">$</span>total <span class="op">~</span><span class="st"> </span>pol<span class="op">$</span>habitat)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo3-2.png" width="672" /></p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="GLM.html#cb171-1"></a><span class="kw">cor</span>(pol<span class="op">$</span>temp, pol<span class="op">$</span>wind)</span></code></pre></div>
<pre><code>## [1] -0.02087349</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="GLM.html#cb173-1"></a><span class="kw">hist</span>(pol<span class="op">$</span>total, <span class="dt">xlab =</span> <span class="st">&quot;Número de interacciones&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Frecuencia relativa&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>, <span class="dt">freq =</span> <span class="ot">FALSE</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))</span>
<span id="cb173-2"><a href="GLM.html#cb173-2"></a></span>
<span id="cb173-3"><a href="GLM.html#cb173-3"></a><span class="co"># Ajuste de distribución a los datos</span></span>
<span id="cb173-4"><a href="GLM.html#cb173-4"></a>sim.pois &lt;-<span class="st"> </span><span class="kw">dpois</span>(<span class="dt">x =</span> <span class="dv">0</span><span class="op">:</span><span class="kw">max</span>(pol<span class="op">$</span>total), <span class="dt">lambda =</span> <span class="kw">mean</span>(pol<span class="op">$</span>total))</span>
<span id="cb173-5"><a href="GLM.html#cb173-5"></a><span class="kw">lines</span>(<span class="dt">x =</span> <span class="dv">0</span><span class="op">:</span><span class="kw">max</span>(pol<span class="op">$</span>total), <span class="dt">y =</span> sim.pois, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo3-3.png" width="672" /></p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="GLM.html#cb174-1"></a><span class="kw">var</span>(pol<span class="op">$</span>total)<span class="op">/</span><span class="kw">mean</span>(pol<span class="op">$</span>total)</span></code></pre></div>
<pre><code>## [1] 30.01128</code></pre>
<div id="chequear-sobredispersión" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.1</span> Chequear sobredispersión<a href="GLM.html#chequear-sobredispersión" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="GLM.html#cb176-1"></a>mqpoi.pol &lt;-<span class="st"> </span><span class="kw">glm</span>(total <span class="op">~</span><span class="st"> </span>habitat <span class="op">+</span><span class="st"> </span>temp <span class="op">+</span><span class="st"> </span>wind, <span class="dt">family =</span> quasipoisson, <span class="dt">data =</span> pol) </span>
<span id="cb176-2"><a href="GLM.html#cb176-2"></a><span class="kw">summary</span>(mqpoi.pol)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = total ~ habitat + temp + wind, family = quasipoisson, 
##     data = pol)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -8.7048  -2.7630  -0.5307   2.2527   8.9461  
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  2.244844   1.518268   1.479  0.14935   
## habitata     0.813256   0.238963   3.403  0.00186 **
## habitatu     0.535908   0.233539   2.295  0.02868 * 
## temp         0.018127   0.016226   1.117  0.27252   
## wind        -0.001247   0.116820  -0.011  0.99155   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 18.37662)
## 
##     Null deviance: 876.87  on 35  degrees of freedom
## Residual deviance: 565.09  on 31  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="GLM.html#cb178-1"></a><span class="kw">library</span>(DHARMa)</span>
<span id="cb178-2"><a href="GLM.html#cb178-2"></a>mpoi.pol &lt;-<span class="st"> </span><span class="kw">glm</span>(total <span class="op">~</span><span class="st"> </span>habitat <span class="op">+</span><span class="st"> </span>temp <span class="op">+</span><span class="st"> </span>wind, <span class="dt">family =</span> poisson, <span class="dt">data =</span> pol)</span>
<span id="cb178-3"><a href="GLM.html#cb178-3"></a><span class="kw">testDispersion</span>(mpoi.pol)</span></code></pre></div>
<p><img src="_main_files/figure-html/sobredispersion-1.png" width="672" /></p>
<pre><code>## 
##  DHARMa nonparametric dispersion test via sd of residuals fitted vs.
##  simulated
## 
## data:  simulationOutput
## dispersion = 21.413, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided</code></pre>
</div>
<div id="validación-del-modelo-quasi-poisson" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.2</span> Validación del modelo quasi-Poisson<a href="GLM.html#validación-del-modelo-quasi-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="GLM.html#cb180-1"></a><span class="kw">plot</span>(<span class="kw">simulateResiduals</span>(<span class="dt">fittedModel =</span> mpoi.pol))</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20glm%20quasipoisson-1.png" width="672" /></p>
</div>
<div id="modelo-binomial-negativo" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.3</span> Modelo binomial negativo<a href="GLM.html#modelo-binomial-negativo" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="GLM.html#cb181-1"></a><span class="kw">library</span>(MASS)</span>
<span id="cb181-2"><a href="GLM.html#cb181-2"></a>mbn.pol &lt;-<span class="st"> </span><span class="kw">glm.nb</span>(total <span class="op">~</span><span class="st"> </span>habitat <span class="op">+</span><span class="st"> </span>temp <span class="op">+</span><span class="st"> </span>wind, <span class="dt">data =</span> pol) </span>
<span id="cb181-3"><a href="GLM.html#cb181-3"></a><span class="kw">summary</span>(mbn.pol)</span></code></pre></div>
<pre><code>## 
## Call:
## glm.nb(formula = total ~ habitat + temp + wind, data = pol, init.theta = 5.957692263, 
##     link = log)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3561  -0.8982  -0.1773   0.5760   1.8680  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.82455    1.28889   2.191  0.02842 *  
## habitata     0.78487    0.19397   4.046  5.2e-05 ***
## habitatu     0.52773    0.18051   2.924  0.00346 ** 
## temp         0.01218    0.01406   0.866  0.38652    
## wind        -0.01878    0.10041  -0.187  0.85161    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(5.9577) family taken to be 1)
## 
##     Null deviance: 58.860  on 35  degrees of freedom
## Residual deviance: 36.513  on 31  degrees of freedom
## AIC: 358.06
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  5.96 
##           Std. Err.:  1.47 
## 
##  2 x log-likelihood:  -346.062</code></pre>
</div>
<div id="validación-del-modelo-binomial-negativo" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.4</span> Validación del modelo binomial negativo<a href="GLM.html#validación-del-modelo-binomial-negativo" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="GLM.html#cb183-1"></a><span class="kw">plot</span>(<span class="kw">simulateResiduals</span>(<span class="dt">fittedModel =</span> mbn.pol))</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20glm%20BN-1.png" width="672" /></p>
</div>
<div id="bondad-del-ajuste-2" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.5</span> Bondad del ajuste<a href="GLM.html#bondad-del-ajuste-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="GLM.html#cb184-1"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(mbn.pol<span class="op">$</span>dev<span class="op">/</span>mbn.pol<span class="op">$</span>null) <span class="co"># Pseudo-R2</span></span></code></pre></div>
<pre><code>## [1] 0.3796712</code></pre>
</div>
<div id="ecuación-2" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.6</span> Ecuación<a href="GLM.html#ecuación-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="GLM.html#cb186-1"></a><span class="kw">extract_eq</span>(mbn.pol, <span class="dt">use_coefs =</span> <span class="ot">TRUE</span>, <span class="dt">fix_signs =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><span class="math display">\[
\log ({ \widehat{E( \operatorname{total} )} })  = 2.82 + 0.78(\operatorname{habitat}_{\operatorname{a}}) + 0.53(\operatorname{habitat}_{\operatorname{u}}) + 0.01(\operatorname{temp}) - 0.02(\operatorname{wind})
\]</span></p>
</div>
<div id="comparaciones-múltiples" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.7</span> Comparaciones múltiples<a href="GLM.html#comparaciones-múltiples" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="GLM.html#cb187-1"></a><span class="kw">library</span>(multcomp) </span></code></pre></div>
<pre><code>## Loading required package: mvtnorm</code></pre>
<pre><code>## Loading required package: TH.data</code></pre>
<pre><code>## 
## Attaching package: &#39;TH.data&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:MASS&#39;:
## 
##     geyser</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="GLM.html#cb192-1"></a>comp &lt;-<span class="st"> </span><span class="kw">glht</span>(mbn.pol, <span class="kw">mcp</span>(<span class="dt">habitat =</span> <span class="st">&quot;Tukey&quot;</span>)) </span>
<span id="cb192-2"><a href="GLM.html#cb192-2"></a><span class="kw">summary</span>(comp) </span></code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: glm.nb(formula = total ~ habitat + temp + wind, data = pol, init.theta = 5.957692263, 
##     link = log)
## 
## Linear Hypotheses:
##            Estimate Std. Error z value Pr(&gt;|z|)    
## a - n == 0   0.7849     0.1940   4.046  &lt; 0.001 ***
## u - n == 0   0.5277     0.1805   2.924  0.00964 ** 
## u - a == 0  -0.2571     0.1785  -1.441  0.31960    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
</div>
<div id="incluyendo-un-offset" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.8</span> Incluyendo un offset<a href="GLM.html#incluyendo-un-offset" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="GLM.html#cb194-1"></a>mbn.pol.off &lt;-<span class="st"> </span><span class="kw">glm.nb</span>(total <span class="op">~</span><span class="st"> </span>habitat <span class="op">+</span><span class="st"> </span>temp <span class="op">+</span><span class="st"> </span>wind <span class="op">+</span><span class="st"> </span><span class="kw">offset</span>(<span class="kw">log</span>(min)), <span class="dt">data =</span> pol)</span>
<span id="cb194-2"><a href="GLM.html#cb194-2"></a><span class="kw">summary</span>(mbn.pol.off)</span></code></pre></div>
<pre><code>## 
## Call:
## glm.nb(formula = total ~ habitat + temp + wind + offset(log(min)), 
##     data = pol, init.theta = 5.957692263, link = log)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3561  -0.8982  -0.1773   0.5760   1.8680  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.67526    1.28889  -1.300  0.19368    
## habitata     0.78487    0.19397   4.046  5.2e-05 ***
## habitatu     0.52773    0.18051   2.924  0.00346 ** 
## temp         0.01218    0.01406   0.866  0.38652    
## wind        -0.01878    0.10041  -0.187  0.85161    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(5.9577) family taken to be 1)
## 
##     Null deviance: 58.860  on 35  degrees of freedom
## Residual deviance: 36.513  on 31  degrees of freedom
## AIC: 358.06
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  5.96 
##           Std. Err.:  1.47 
## 
##  2 x log-likelihood:  -346.062</code></pre>
</div>
<div id="gráficos-de-los-modelos" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.2.2.9</span> Gráficos de los modelos<a href="GLM.html#gráficos-de-los-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="GLM.html#cb196-1"></a><span class="kw">layout</span>(<span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb196-2"><a href="GLM.html#cb196-2"></a><span class="kw">visreg</span>(<span class="dt">fit =</span> mbn.pol, <span class="dt">xvar =</span> <span class="st">&quot;habitat&quot;</span>, <span class="dt">scale =</span> <span class="st">&quot;response&quot;</span>, <span class="dt">cond =</span> <span class="kw">list</span>(<span class="dt">temp =</span> <span class="kw">mean</span>(pol<span class="op">$</span>temp), <span class="dt">wind =</span> <span class="kw">mean</span>(pol<span class="op">$</span>wind)), <span class="dt">xlab =</span> <span class="st">&quot;Habitat&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Numero de visitas&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;GLM binomial negativo&quot;</span>)</span>
<span id="cb196-3"><a href="GLM.html#cb196-3"></a><span class="kw">visreg</span>(<span class="dt">fit =</span> mbn.pol.off, <span class="dt">xvar =</span> <span class="st">&quot;habitat&quot;</span>, <span class="dt">scale =</span> <span class="st">&quot;response&quot;</span>, <span class="dt">cond =</span> <span class="kw">list</span>(<span class="dt">temp =</span> <span class="kw">mean</span>(pol<span class="op">$</span>temp), <span class="dt">wind =</span> <span class="kw">mean</span>(pol<span class="op">$</span>wind), <span class="dt">min =</span> <span class="dv">1</span>), <span class="dt">xlab =</span> <span class="st">&quot;Habitat&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Tasa de visitas (ind/min)&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;GLM binomial negativo con offset&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/grafico%20glm%20BN-1.png" width="672" /></p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="GLM.html#cb197-1"></a><span class="kw">layout</span>(<span class="dv">1</span>)</span></code></pre></div>
</div>
</div>
</div>
<div id="modelo-lineal-general" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.3</span> Modelo lineal general<a href="GLM.html#modelo-lineal-general" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Palacio et al. (2014) estudiaron la selección natural mediada por aves frugívoras sobre rasgos de los frutos de <em>Celtis tala</em> (<code>frutos Celtis 2013.txt</code>), incluyendo el diámetro (<code>diam</code>), peso (<code>peso</code>), concentración de azúcares (<code>az</code>), peso de pulpa (<code>pulpa</code>), peso de semilla (<code>sem</code>) y relación peso de pulpa/peso de semilla (<code>pulpa.sem</code>). Analizar qué factores explican el tamaño del fruto.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="GLM.html#cb198-1"></a>celtis &lt;-<span class="st"> </span><span class="kw">read.delim</span>(<span class="st">&quot;frutos Celtis 2013.csv&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>)</span>
<span id="cb198-2"><a href="GLM.html#cb198-2"></a><span class="kw">str</span>(celtis)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    617 obs. of  8 variables:
##  $ planta   : chr  &quot;P1-10&quot; &quot;P1-10&quot; &quot;P1-10&quot; &quot;P1-10&quot; ...
##  $ parche   : chr  &quot;P1&quot; &quot;P1&quot; &quot;P1&quot; &quot;P1&quot; ...
##  $ diam     : num  9.26 8.12 9.01 8.57 7.48 ...
##  $ peso     : num  0.414 0.291 0.387 0.339 0.222 0.307 0.318 0.35 0.259 0.294 ...
##  $ az       : num  18.5 21.5 18.5 23.5 16.5 ...
##  $ pulpa    : num  0.361 0.252 0.331 0.287 0.177 0.252 0.272 0.292 0.217 0.253 ...
##  $ sem      : num  0.0523 0.0393 0.0556 0.0519 0.0443 0.0555 0.0453 0.0581 0.0419 0.0417 ...
##  $ pulpa.sem: num  6.91 6.41 5.96 5.53 4 ...</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="GLM.html#cb200-1"></a><span class="kw">pairs</span>(celtis[, <span class="dv">3</span><span class="op">:</span><span class="dv">7</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/lm-1.png" width="672" /></p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="GLM.html#cb201-1"></a><span class="kw">round</span>(<span class="kw">cor</span>(celtis[, <span class="dv">4</span><span class="op">:</span><span class="dv">7</span>], <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##        peso    az pulpa  sem
## peso   1.00 -0.33  0.99 0.45
## az    -0.33  1.00 -0.37 0.20
## pulpa  0.99 -0.37  1.00 0.34
## sem    0.45  0.20  0.34 1.00</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="GLM.html#cb203-1"></a><span class="kw">hist</span>(celtis<span class="op">$</span>diam, <span class="dt">xlab =</span> <span class="st">&quot;Diametro (mm)&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Frecuencia&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/lm-2.png" width="672" /></p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="GLM.html#cb204-1"></a>mlg &lt;-<span class="st"> </span><span class="kw">glm</span>(diam <span class="op">~</span><span class="st"> </span>az <span class="op">+</span><span class="st"> </span>sem, <span class="dt">family =</span> gaussian, <span class="dt">data =</span> celtis)</span>
<span id="cb204-2"><a href="GLM.html#cb204-2"></a><span class="kw">summary</span>(mlg)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = diam ~ az + sem, family = gaussian, data = celtis)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -1.96247  -0.49375  -0.01025   0.46537   2.04017  
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  8.750071   0.176681   49.52   &lt;2e-16 ***
## az          -0.094204   0.006975  -13.51   &lt;2e-16 ***
## sem         39.834317   2.400758   16.59   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 0.4902039)
## 
##     Null deviance: 487.54  on 613  degrees of freedom
## Residual deviance: 299.51  on 611  degrees of freedom
##   (3 observations deleted due to missingness)
## AIC: 1309.7
## 
## Number of Fisher Scoring iterations: 2</code></pre>
</div>
<div id="glm-gamma" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.4</span> GLM Gamma<a href="GLM.html#glm-gamma" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Allen et al. (2015) analizaron el efecto de grandes carnívoros (<span class="math inline">\(Ursus americanus\)</span> y <span class="math inline">\(Puma concolor\)</span>) sobre la actividad de carroñeros. Registraron la duración media del evento de alimentación (<code>duration</code>) por carroñeros en sitios con cadáveres producto de pumas y sitios control donde se colocaron cadáveres colectados en la ruta (<code>trat</code>).</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="GLM.html#cb206-1"></a><span class="co"># Gráficos exploratorios </span></span>
<span id="cb206-2"><a href="GLM.html#cb206-2"></a>datos &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;puma.txt&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)</span>
<span id="cb206-3"><a href="GLM.html#cb206-3"></a>datos<span class="op">$</span>trat &lt;-<span class="st"> </span><span class="kw">as.factor</span>(datos<span class="op">$</span>trat)</span>
<span id="cb206-4"><a href="GLM.html#cb206-4"></a>P &lt;-<span class="st"> </span><span class="kw">subset</span>(datos, trat <span class="op">==</span><span class="st"> &quot;Puma_Kill&quot;</span>) </span>
<span id="cb206-5"><a href="GLM.html#cb206-5"></a>C &lt;-<span class="st"> </span><span class="kw">subset</span>(datos, trat <span class="op">==</span><span class="st"> &quot;Control&quot;</span>) </span>
<span id="cb206-6"><a href="GLM.html#cb206-6"></a><span class="kw">layout</span>(<span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>)) </span>
<span id="cb206-7"><a href="GLM.html#cb206-7"></a><span class="kw">hist</span>(P<span class="op">$</span>duration) </span>
<span id="cb206-8"><a href="GLM.html#cb206-8"></a><span class="kw">hist</span>(C<span class="op">$</span>duration) </span></code></pre></div>
<p><img src="_main_files/figure-html/glm%20gamma-1.png" width="672" /></p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="GLM.html#cb207-1"></a><span class="kw">layout</span>(<span class="dv">1</span>) </span>
<span id="cb207-2"><a href="GLM.html#cb207-2"></a><span class="kw">boxplot</span>(datos<span class="op">$</span>duration <span class="op">~</span><span class="st"> </span>datos<span class="op">$</span>trat) </span></code></pre></div>
<p><img src="_main_files/figure-html/glm%20gamma-2.png" width="672" /></p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="GLM.html#cb208-1"></a><span class="co"># GLM Gamma </span></span>
<span id="cb208-2"><a href="GLM.html#cb208-2"></a>m.Gamma &lt;-<span class="st"> </span><span class="kw">glm</span>(duration <span class="op">~</span><span class="st"> </span>trat, <span class="dt">family =</span> Gamma, <span class="dt">data =</span> datos) </span>
<span id="cb208-3"><a href="GLM.html#cb208-3"></a><span class="kw">summary</span>(m.Gamma)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = duration ~ trat, family = Gamma, data = datos)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7942  -0.8165  -0.1525   0.3143   2.2724  
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    0.06639    0.01251   5.308 2.43e-06 ***
## tratPuma_Kill  0.03731    0.02067   1.805    0.077 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Gamma family taken to be 0.7808647)
## 
##     Null deviance: 35.695  on 52  degrees of freedom
## Residual deviance: 33.092  on 51  degrees of freedom
## AIC: 363.65
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="GLM.html#cb210-1"></a><span class="co"># Comparaciones múltiples </span></span>
<span id="cb210-2"><a href="GLM.html#cb210-2"></a><span class="kw">library</span>(multcomp)</span>
<span id="cb210-3"><a href="GLM.html#cb210-3"></a>comp &lt;-<span class="st"> </span><span class="kw">glht</span>(m.Gamma, <span class="kw">mcp</span>(<span class="dt">trat =</span> <span class="st">&quot;Tukey&quot;</span>)) </span>
<span id="cb210-4"><a href="GLM.html#cb210-4"></a><span class="kw">summary</span>(comp)</span></code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: glm(formula = duration ~ trat, family = Gamma, data = datos)
## 
## Linear Hypotheses:
##                          Estimate Std. Error z value Pr(&gt;|z|)  
## Puma_Kill - Control == 0  0.03731    0.02067   1.805   0.0711 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
</div>
<div id="actividades-1" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.5</span> Actividades<a href="GLM.html#actividades-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="ejercicio-2.1" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.5.1</span> Ejercicio 2.1<a href="GLM.html#ejercicio-2.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Identifique qué tipo de distribuciones de probabilidad utilizaría para las siguientes variables de respuesta. Justifique en cada caso.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Densidad de especies de plantas en parcelas de un bosque.</p></li>
<li><p>Probabilidad de detección de una especie de anfibio en charcas temporarias.</p></li>
<li><p>La tasa de crecimiento en pichones de una especie de ave.</p></li>
<li><p>El sexo en una especie de lagarto.</p></li>
</ol>
</div>
<div id="ejercicio-2.2" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.5.2</span> Ejercicio 2.2<a href="GLM.html#ejercicio-2.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se estimó la prevalencia del parásito <em>Elaphostrongylus cervi</em> en ciervos colorados de granjas de España (<code>Tbdeer</code>). En cada granja (<code>Farm</code>) se muestreó un grupo de animales (<code>DeerSampledCervi</code>) y se registró si eran positivos para la enfermedad (<code>DeerPosCervi</code>). Además, se registraron variables de hábitat, como porcentaje de áreas abiertas (<code>OpenLand</code>), arbustos (<code>ScrubLand</code>) y plantaciones de pino (<code>PinePlantation</code>), densidad de plantas y árboles de <em>Quercus</em> sp. (<code>QuercusPlants</code>, <code>QuercusTrees</code>). También se estimaron abundancias relativas de jabalí (<code>WildBoarIndex</code>) y ciervo colorado (<code>RedDeerIndex</code>), área del campo (<code>EstateSize</code>) y si el campo estaba cercado (1 = cercado, 0 = no cercado).</p>
<ul>
<li><p>Determine, cuáles de estas variables están involucradas en la prevalencia de la enfermedad.</p></li>
<li><p>Valide y grafique el modelo resultante.</p></li>
</ul>
</div>
<div id="ejercicio-2.3" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.5.3</span> Ejercicio 2.3<a href="GLM.html#ejercicio-2.3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Simule un modelo lineal general (utilice la función <code>rnorm</code>) con dos variables (una con un efecto positivo y otra con un efecto negativo sobre la respuesta) y ajuste un modelo con las funciones <code>lm</code> y <code>glm</code>. Compare ambos modelos ¿Qué conclusión obtiene?</p>
<div id="ejercicio-2.4" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.5.3.1</span> Ejercicio 2.4<a href="GLM.html#ejercicio-2.4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Desarrolle un script para calcular el R<sup>2</sup> de Tjur utilizando el GLM binomial de Solea.txt, donde:</p>
<p><span class="math display">\[R^{2}_{Tjur} = \frac{\sum \hat{p}(y = 1)}{n_1}\ + \frac{\sum \hat{p}(y = 0)}{n_0}\]</span></p>
<p>Corrobore el resultado con la función <code>r2_tjur</code> del paquete <code>performance</code> ¿En qué situación hipotética el <span class="math inline">\(R^2\)</span> vale 0?</p>
</div>
</div>
</div>
<div id="conteos-ii" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.6</span> Conteos II<a href="GLM.html#conteos-ii" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="modelos-truncados-en-cero" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.6.1</span> Modelos truncados en cero<a href="GLM.html#modelos-truncados-en-cero" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Santos et al. (2011) estudiaron la probabilidad de persistencia de las carcasas de animales muertos en ruta (<code>Snakes.txt</code>). La variable respuesta es la cantidad de días que perduraban las carcasas sin ser removidas (<code>N_days</code>). Las variables explicatorias son la longitud de cada especie (<code>Size_cm</code>), la proporción de días con lluvia (<code>PDayRain</code>), las precipitaciones totales (<code>Tot_Rain</code>), la temperatura diaria promedio (<code>Temp_avg</code>), la identidad de la ruta que representa la intesidad del tráfico (<code>Road</code>; EN114 tiene alto tránsito, EN4 tiene tráfico medio, y EN370_EN114_4 tiene bajo tráfico), la ubicación en la ruta (<code>Road_Loc</code>; L = asfalto, V = borde), la estación (<code>Season</code>), y la especie (<code>Species</code>).</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="GLM.html#cb212-1"></a><span class="co"># Analisis exploratorio</span></span>
<span id="cb212-2"><a href="GLM.html#cb212-2"></a>serp &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;Snakes.txt&quot;</span>, <span class="dt">header =</span> T) </span>
<span id="cb212-3"><a href="GLM.html#cb212-3"></a><span class="kw">str</span>(serp)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    130 obs. of  11 variables:
##  $ ID      : int  2176 2448 2917 2927 2845 2849 2860 2760 2758 2764 ...
##  $ Road    : chr  &quot;EN114&quot; &quot;EN114&quot; &quot;EN114&quot; &quot;EN114&quot; ...
##  $ Month   : chr  &quot;Jul&quot; &quot;Aug&quot; &quot;Oct&quot; &quot;Oct&quot; ...
##  $ Season  : chr  &quot;Summer&quot; &quot;Summer&quot; &quot;Autumn&quot; &quot;Autumn&quot; ...
##  $ N_days  : int  4 1 4 2 1 1 2 1 2 2 ...
##  $ Species : chr  &quot;Coluberhippocrepis&quot; &quot;Elaphescalaris&quot; &quot;Elaphescalaris&quot; &quot;Elaphescalaris&quot; ...
##  $ Road_Loc: chr  &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot; ...
##  $ Size_cm : int  115 150 150 150 150 150 150 150 150 150 ...
##  $ PDayRain: num  0.75 0 1 1 0 0 0 0 0 0 ...
##  $ Tot_Rain: num  15 0 40.2 35.6 0 0 0 0 0 0 ...
##  $ Temp_avg: num  24.6 27.4 19.1 17.8 22.3 22.3 19.7 19.9 19.4 19.4 ...</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="GLM.html#cb214-1"></a><span class="kw">plot</span>(<span class="kw">table</span>(serp<span class="op">$</span>N_days))</span></code></pre></div>
<p><img src="_main_files/figure-html/explo6-1.png" width="672" /></p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="GLM.html#cb215-1"></a><span class="kw">mean</span>(serp<span class="op">$</span>N_days)</span></code></pre></div>
<pre><code>## [1] 2.2</code></pre>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="GLM.html#cb217-1"></a><span class="kw">pairs</span>(serp[, <span class="kw">c</span>(<span class="st">&quot;PDayRain&quot;</span>, <span class="st">&quot;Tot_Rain&quot;</span>, <span class="st">&quot;Temp_avg&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/explo6-2.png" width="672" /></p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="GLM.html#cb218-1"></a><span class="kw">round</span>(<span class="kw">cor</span>(serp[, <span class="kw">c</span>(<span class="st">&quot;PDayRain&quot;</span>, <span class="st">&quot;Tot_Rain&quot;</span>, <span class="st">&quot;Temp_avg&quot;</span>)]), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##          PDayRain Tot_Rain Temp_avg
## PDayRain     1.00     0.42     -0.5
## Tot_Rain     0.42     1.00     -0.3
## Temp_avg    -0.50    -0.30      1.0</code></pre>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="GLM.html#cb220-1"></a><span class="kw">boxplot</span>(serp<span class="op">$</span>PDayRain <span class="op">~</span><span class="st"> </span>serp<span class="op">$</span>Season)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo6-3.png" width="672" /></p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="GLM.html#cb221-1"></a><span class="kw">boxplot</span>(serp<span class="op">$</span>Tot_Rain <span class="op">~</span><span class="st"> </span>serp<span class="op">$</span>Season)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo6-4.png" width="672" /></p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="GLM.html#cb222-1"></a><span class="kw">boxplot</span>(serp<span class="op">$</span>Temp_avg <span class="op">~</span><span class="st"> </span>serp<span class="op">$</span>Season)</span></code></pre></div>
<p><img src="_main_files/figure-html/explo6-5.png" width="672" /></p>
<div id="comparación-con-el-glm-poisson" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.1.1</span> Comparación con el GLM Poisson<a href="GLM.html#comparación-con-el-glm-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="GLM.html#cb223-1"></a>m.pois &lt;-<span class="st"> </span><span class="kw">glm</span>(N_days <span class="op">~</span><span class="st"> </span>Size_cm <span class="op">+</span><span class="st"> </span>PDayRain <span class="op">+</span><span class="st"> </span>Tot_Rain <span class="op">+</span><span class="st"> </span>Road <span class="op">+</span><span class="st"> </span>Size_cm <span class="op">+</span><span class="st"> </span>Road_Loc <span class="op">+</span><span class="st"> </span>Size_cm<span class="op">:</span>PDayRain, <span class="dt">family =</span> poisson, <span class="dt">data =</span> serp)</span>
<span id="cb223-2"><a href="GLM.html#cb223-2"></a><span class="kw">summary</span>(m.pois)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = N_days ~ Size_cm + PDayRain + Tot_Rain + Road + 
##     Size_cm + Road_Loc + Size_cm:PDayRain, family = poisson, 
##     data = serp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0869  -0.7901  -0.4193   0.2448   5.9495  
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)       -0.114527   0.463263  -0.247 0.804739    
## Size_cm            0.004782   0.002965   1.613 0.106848    
## PDayRain           0.957714   0.768545   1.246 0.212713    
## Tot_Rain           0.022763   0.003797   5.994 2.04e-09 ***
## RoadEN370_EN114_4 -0.146154   0.172785  -0.846 0.397626    
## RoadEN4           -0.352271   0.147973  -2.381 0.017282 *  
## Road_LocV          0.530610   0.158214   3.354 0.000797 ***
## Size_cm:PDayRain  -0.006869   0.005161  -1.331 0.183215    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 226.38  on 129  degrees of freedom
## Residual deviance: 166.85  on 122  degrees of freedom
## AIC: 498.68
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="glm-poisson-truncado-en-cero" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.1.2</span> GLM Poisson truncado en cero<a href="GLM.html#glm-poisson-truncado-en-cero" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="GLM.html#cb225-1"></a><span class="kw">library</span>(VGAM)</span></code></pre></div>
<pre><code>## Warning: package &#39;VGAM&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Loading required package: stats4</code></pre>
<pre><code>## Loading required package: splines</code></pre>
<pre><code>## 
## Attaching package: &#39;VGAM&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     logit</code></pre>
<pre><code>## The following objects are masked from &#39;package:psych&#39;:
## 
##     fisherz, logistic, logit</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="GLM.html#cb232-1"></a>m.pois.trun &lt;-<span class="st"> </span><span class="kw">vglm</span>(N_days <span class="op">~</span><span class="st"> </span>Size_cm <span class="op">+</span><span class="st"> </span>PDayRain <span class="op">+</span><span class="st"> </span>Tot_Rain <span class="op">+</span><span class="st"> </span>Road <span class="op">+</span><span class="st"> </span>Size_cm <span class="op">+</span><span class="st"> </span>Road_Loc <span class="op">+</span><span class="st"> </span>Size_cm<span class="op">:</span>PDayRain, <span class="dt">family =</span> pospoisson, <span class="dt">control =</span>  <span class="kw">vglm.control</span>(<span class="dt">maxit =</span> <span class="dv">100</span>), <span class="dt">data =</span> serp)</span>
<span id="cb232-2"><a href="GLM.html#cb232-2"></a><span class="kw">summary</span>(m.pois.trun)</span></code></pre></div>
<pre><code>## 
## Call:
## vglm(formula = N_days ~ Size_cm + PDayRain + Tot_Rain + Road + 
##     Size_cm + Road_Loc + Size_cm:PDayRain, family = pospoisson, 
##     data = serp, control = vglm.control(maxit = 100))
## 
## Coefficients: 
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)       -1.214880   0.764099  -1.590  0.11185    
## Size_cm            0.009725   0.004830   2.014  0.04406 *  
## PDayRain           1.782494   1.097674   1.624  0.10440    
## Tot_Rain           0.028863   0.004270   6.760 1.38e-11 ***
## RoadEN370_EN114_4 -0.217333   0.225081  -0.966  0.33425    
## RoadEN4           -0.558705   0.181936  -3.071  0.00213 ** 
## Road_LocV          0.811896   0.200842   4.042 5.29e-05 ***
## Size_cm:PDayRain  -0.012131   0.007245  -1.674  0.09404 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Name of linear predictor: loglink(lambda) 
## 
## Log-likelihood: -211.1832 on 122 degrees of freedom
## 
## Number of Fisher scoring iterations: 5 
## 
## No Hauck-Donner effect found in any of the estimates</code></pre>
</div>
<div id="glm-binomial-negativo-truncado-en-cero" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.1.3</span> GLM binomial negativo truncado en cero<a href="GLM.html#glm-binomial-negativo-truncado-en-cero" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="GLM.html#cb234-1"></a>m.nb.trun &lt;-<span class="st"> </span><span class="kw">vglm</span>(N_days <span class="op">~</span><span class="st"> </span>Size_cm <span class="op">+</span><span class="st"> </span>PDayRain <span class="op">+</span><span class="st"> </span>Tot_Rain <span class="op">+</span><span class="st"> </span>Road <span class="op">+</span><span class="st"> </span>Size_cm <span class="op">+</span><span class="st"> </span>Road_Loc <span class="op">+</span><span class="st"> </span>Size_cm<span class="op">:</span>PDayRain, <span class="dt">family =</span> posnegbinomial, <span class="dt">control =</span>  <span class="kw">vglm.control</span>(<span class="dt">maxit =</span> <span class="dv">100</span>), <span class="dt">data =</span> serp)</span></code></pre></div>
<pre><code>## Warning in slot(family, &quot;linkinv&quot;)(eta, extra = extra): estimates of &#39;size&#39; are
## very small. Taking evasive action.</code></pre>
<pre><code>## Warning in slot(family, &quot;validparams&quot;)(eta, y = y, extra = extra): parameter
## &#39;size&#39; has very large values relative to &#39;munb&#39;; try fitting a positive-Poisson
## model instead.</code></pre>
<pre><code>## Warning in eval(slot(family, &quot;deriv&quot;)): solution near the boundary; either there
## is no need to fit a positive NBD or the distribution is centred on the value 1</code></pre>
<pre><code>## Warning in slot(family, &quot;validparams&quot;)(eta, y, extra = extra): parameter &#39;size&#39;
## has very large values relative to &#39;munb&#39;; try fitting a positive-Poisson model
## instead.</code></pre>
<pre><code>## Warning in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2, :
## iterations terminated because half-step sizes are very small</code></pre>
<pre><code>## Warning in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2, : some
## quantities such as z, residuals, SEs may be inaccurate due to convergence at a
## half-step</code></pre>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="GLM.html#cb241-1"></a><span class="kw">summary</span>(m.nb.trun)</span></code></pre></div>
<pre><code>## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1</code></pre>
<pre><code>## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1

## Warning in eval(expr): solution near the boundary; either there is no need to
## fit a positive NBD or the distribution is centred on the value 1</code></pre>
<pre><code>## 
## Call:
## vglm(formula = N_days ~ Size_cm + PDayRain + Tot_Rain + Road + 
##     Size_cm + Road_Loc + Size_cm:PDayRain, family = posnegbinomial, 
##     data = serp, control = vglm.control(maxit = 100))
## 
## Coefficients: 
##                     Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept):1     -18.650956   9.622924       NA       NA    
## (Intercept):2     -19.201942   0.087878 -218.508   &lt;2e-16 ***
## Size_cm             0.006975   0.062006    0.112    0.910    
## PDayRain            1.196235  18.692101    0.064    0.949    
## Tot_Rain            0.067164   0.117128    0.573    0.566    
## RoadEN370_EN114_4  -0.276550   4.059935   -0.068    0.946    
## RoadEN4            -0.558499   3.643634   -0.153    0.878    
## Road_LocV           1.072722   3.817984    0.281    0.779    
## Size_cm:PDayRain   -0.009605   0.126436   -0.076    0.939    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Names of linear predictors: loglink(munb), loglink(size)
## 
## Log-likelihood: -186.7285 on 251 degrees of freedom
## 
## Number of Fisher scoring iterations: 3 
## 
## Warning: Hauck-Donner effect detected in the following estimate(s):
## &#39;(Intercept):1&#39;</code></pre>
</div>
<div id="comparación-de-coeficientes-entre-modelos" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.1.4</span> Comparación de coeficientes entre modelos<a href="GLM.html#comparación-de-coeficientes-entre-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="GLM.html#cb245-1"></a><span class="kw">data.frame</span>(<span class="dt">coef.Poisson =</span> <span class="kw">summary</span>(m.pois)<span class="op">$</span>coeff[, <span class="dv">1</span>], </span>
<span id="cb245-2"><a href="GLM.html#cb245-2"></a>           <span class="dt">coef.Poisson.truncado =</span> <span class="kw">summary</span>(m.pois.trun)<span class="op">@</span>coef3[, <span class="dv">1</span>])</span></code></pre></div>
<pre><code>##                   coef.Poisson coef.Poisson.truncado
## (Intercept)       -0.114527460          -1.214879652
## Size_cm            0.004781715           0.009724801
## PDayRain           0.957714141           1.782494406
## Tot_Rain           0.022763117           0.028863331
## RoadEN370_EN114_4 -0.146153654          -0.217333044
## RoadEN4           -0.352270790          -0.558704924
## Road_LocV          0.530609962           0.811896312
## Size_cm:PDayRain  -0.006868709          -0.012131485</code></pre>
</div>
</div>
<div id="modelos-inflados-en-ceros" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.6.2</span> Modelos inflados en ceros<a href="GLM.html#modelos-inflados-en-ceros" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hemmingsen et al. (2005) analizaron las infecciones por <em>Trypanosoma</em> en bacalaos (<em>Gadus morhua</em>) durante cruceros anuales en la costa norte de Noruega (<code>ParasiteCod.txt</code>). La variable respuesta es la prevalencia de parásitos (<code>Prevalence</code>). Posibles variables explicatorias son el año (<code>Year</code>), el área (<code>Area</code>) y la profundidad de captura (<code>Depth</code>).</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="GLM.html#cb247-1"></a><span class="co"># Análisis exploratorio</span></span>
<span id="cb247-2"><a href="GLM.html#cb247-2"></a>parasitos &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;ParasiteCod.txt&quot;</span>, <span class="dt">header =</span> T) </span>
<span id="cb247-3"><a href="GLM.html#cb247-3"></a><span class="kw">str</span>(parasitos)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1254 obs. of  11 variables:
##  $ Sample    : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Intensity : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Prevalence: int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Year      : int  1999 1999 1999 1999 1999 1999 1999 1999 1999 1999 ...
##  $ Depth     : int  220 220 220 220 220 220 220 194 194 194 ...
##  $ Weight    : int  148 144 146 138 40 68 52 3848 2576 1972 ...
##  $ Length    : int  26 26 27 26 17 20 19 77 67 60 ...
##  $ Sex       : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Stage     : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Age       : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Area      : int  2 2 2 2 2 2 2 3 3 3 ...</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="GLM.html#cb249-1"></a><span class="kw">plot</span>(<span class="kw">table</span>(parasitos<span class="op">$</span>Intensity))</span></code></pre></div>
<p><img src="_main_files/figure-html/explo7-1.png" width="672" /></p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="GLM.html#cb250-1"></a><span class="kw">table</span>(parasitos<span class="op">$</span>Intensity)[<span class="dv">1</span>] <span class="co"># Número de ceros observados</span></span></code></pre></div>
<pre><code>##   0 
## 654</code></pre>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="GLM.html#cb252-1"></a><span class="co"># Ajuste de distribución a los datos</span></span>
<span id="cb252-2"><a href="GLM.html#cb252-2"></a>xIntensity &lt;-<span class="st"> </span><span class="kw">mean</span>(parasitos<span class="op">$</span>Intensity, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb252-3"><a href="GLM.html#cb252-3"></a>sim.pois &lt;-<span class="st"> </span><span class="kw">dpois</span>(<span class="dt">x =</span> <span class="dv">0</span><span class="op">:</span><span class="kw">max</span>(parasitos<span class="op">$</span>Intensity, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dt">lambda =</span> xIntensity)</span>
<span id="cb252-4"><a href="GLM.html#cb252-4"></a>ndatos &lt;-<span class="st"> </span><span class="kw">length</span>(<span class="kw">na.omit</span>(parasitos<span class="op">$</span>Intensity))</span>
<span id="cb252-5"><a href="GLM.html#cb252-5"></a>random.sample.pois &lt;-<span class="st"> </span><span class="kw">rpois</span>(<span class="dt">n =</span> ndatos, <span class="dt">lambda =</span> xIntensity)</span>
<span id="cb252-6"><a href="GLM.html#cb252-6"></a><span class="kw">plot</span>(<span class="kw">table</span>(random.sample.pois))</span></code></pre></div>
<p><img src="_main_files/figure-html/explo7-2.png" width="672" /></p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="GLM.html#cb253-1"></a><span class="kw">dpois</span>(<span class="dt">x =</span> <span class="dv">0</span>, <span class="dt">lambda =</span> xIntensity) <span class="co"># Probabilidad de observar un cero</span></span></code></pre></div>
<pre><code>## [1] 0.002064314</code></pre>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="GLM.html#cb255-1"></a><span class="kw">table</span>(random.sample.pois) <span class="co"># Numero de ceros esperados</span></span></code></pre></div>
<pre><code>## random.sample.pois
##   1   2   3   4   5   6   7   8   9  10  11  12  13 
##  17  56 109 153 187 171 170 122  96  54  37  20   5</code></pre>
<div id="modelos-de-dos-partes-o-valla-zap-y-zanb" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.2.1</span> Modelos de dos partes o “valla” (ZAP y ZANB)<a href="GLM.html#modelos-de-dos-partes-o-valla-zap-y-zanb" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="GLM.html#cb257-1"></a><span class="co"># La primera parte de la formula contiene las covariables para el proceso de conteo, la segunda parte contiene las covariables para la probabilidad de los falsos ceros.</span></span>
<span id="cb257-2"><a href="GLM.html#cb257-2"></a><span class="kw">library</span>(pscl)</span></code></pre></div>
<pre><code>## Warning: package &#39;pscl&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Classes and Methods for R developed in the
## Political Science Computational Laboratory
## Department of Political Science
## Stanford University
## Simon Jackman
## hurdle and zeroinfl functions by Achim Zeileis</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="GLM.html#cb260-1"></a>ZAP &lt;-<span class="st"> </span><span class="kw">hurdle</span>(Intensity <span class="op">~</span><span class="st"> </span>Depth <span class="op">|</span><span class="st"> </span>Length <span class="op">+</span><span class="st"> </span>Depth, <span class="dt">dist =</span> <span class="st">&quot;poisson&quot;</span>, </span>
<span id="cb260-2"><a href="GLM.html#cb260-2"></a><span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>, <span class="dt">data =</span> parasitos)</span>
<span id="cb260-3"><a href="GLM.html#cb260-3"></a><span class="kw">summary</span>(ZAP)</span></code></pre></div>
<pre><code>## 
## Call:
## hurdle(formula = Intensity ~ Depth | Length + Depth, data = parasitos, 
##     dist = &quot;poisson&quot;, link = &quot;logit&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -1.3420 -0.8995 -0.6450 -0.2622 32.6701 
## 
## Count model coefficients (truncated poisson with log link):
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) 1.7740079  0.0412390   43.02   &lt;2e-16 ***
## Depth       0.0041351  0.0001857   22.27   &lt;2e-16 ***
## Zero hurdle model coefficients (binomial with logit link):
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.6523797  0.2870146  -5.757 8.56e-09 ***
## Length       0.0039426  0.0042165   0.935     0.35    
## Depth        0.0070509  0.0008584   8.214  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Number of iterations in BFGS optimization: 10 
## Log-likelihood: -8542 on 5 Df</code></pre>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="GLM.html#cb262-1"></a>ZANB &lt;-<span class="st"> </span><span class="kw">hurdle</span>(Intensity <span class="op">~</span><span class="st"> </span>Depth <span class="op">|</span><span class="st"> </span>Length <span class="op">+</span><span class="st"> </span>Depth, <span class="dt">dist =</span> <span class="st">&quot;negbin&quot;</span>, </span>
<span id="cb262-2"><a href="GLM.html#cb262-2"></a><span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>, <span class="dt">data =</span> parasitos)</span>
<span id="cb262-3"><a href="GLM.html#cb262-3"></a><span class="kw">summary</span>(ZANB)</span></code></pre></div>
<pre><code>## 
## Call:
## hurdle(formula = Intensity ~ Depth | Length + Depth, data = parasitos, 
##     dist = &quot;negbin&quot;, link = &quot;logit&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -0.4350 -0.3729 -0.3281 -0.1126 16.3175 
## 
## Count model coefficients (truncated negbin with log link):
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.415345   0.844211  -0.492 0.622725    
## Depth        0.006271   0.001537   4.080 4.51e-05 ***
## Log(theta)  -3.019216   0.867902  -3.479 0.000504 ***
## Zero hurdle model coefficients (binomial with logit link):
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.6523797  0.2870146  -5.757 8.56e-09 ***
## Length       0.0039426  0.0042165   0.935     0.35    
## Depth        0.0070509  0.0008584   8.214  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta: count = 0.0488
## Number of iterations in BFGS optimization: 16 
## Log-likelihood: -2559 on 6 Df</code></pre>
</div>
<div id="comparación-de-zap-y-zanb" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.2.2</span> Comparación de ZAP y ZANB<a href="GLM.html#comparación-de-zap-y-zanb" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="GLM.html#cb264-1"></a><span class="kw">library</span>(lmtest)</span></code></pre></div>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre><code>## 
## Attaching package: &#39;lmtest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:VGAM&#39;:
## 
##     lrtest</code></pre>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="GLM.html#cb270-1"></a><span class="kw">lrtest</span>(ZAP, ZANB) <span class="co"># Test de razón de verosimilitud</span></span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: Intensity ~ Depth | Length + Depth
## Model 2: Intensity ~ Depth | Length + Depth
##   #Df  LogLik Df Chisq Pr(&gt;Chisq)    
## 1   5 -8542.3                        
## 2   6 -2559.4  1 11966  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="GLM.html#cb272-1"></a><span class="kw">AIC</span>(ZAP, ZANB)</span></code></pre></div>
<pre><code>##      df      AIC
## ZAP   5 17094.58
## ZANB  6  5130.85</code></pre>
</div>
<div id="validación" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.2.3</span> Validación<a href="GLM.html#validación" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="GLM.html#cb274-1"></a>resid &lt;-<span class="st"> </span><span class="kw">residuals</span>(ZANB, <span class="dt">type =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb274-2"><a href="GLM.html#cb274-2"></a><span class="kw">plot</span>(resid, <span class="kw">predict</span>(ZANB), <span class="dt">xlab =</span> <span class="st">&quot;Residuos&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Predichos&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20ZANB-1.png" width="672" /></p>
</div>
<div id="interpretación-y-gráficos-del-modelo" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.2.4</span> Interpretación y gráficos del modelo<a href="GLM.html#interpretación-y-gráficos-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="GLM.html#cb275-1"></a><span class="co"># Proceso de falsos ceros</span></span>
<span id="cb275-2"><a href="GLM.html#cb275-2"></a>Depth &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">min</span>(parasitos<span class="op">$</span>Depth), <span class="kw">max</span>(parasitos<span class="op">$</span>Depth), <span class="dt">length =</span> <span class="dv">500</span>)</span>
<span id="cb275-3"><a href="GLM.html#cb275-3"></a>Length &lt;-<span class="st"> </span><span class="kw">mean</span>(parasitos<span class="op">$</span>Length, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb275-4"><a href="GLM.html#cb275-4"></a>zero.model.coef &lt;-<span class="st"> </span>ZANB<span class="op">$</span>coefficients<span class="op">$</span>zero <span class="co"># Coeficientes</span></span>
<span id="cb275-5"><a href="GLM.html#cb275-5"></a>u &lt;-<span class="st"> </span>zero.model.coef[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>Length<span class="op">*</span>zero.model.coef[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>Depth<span class="op">*</span>zero.model.coef[<span class="dv">3</span>]</span>
<span id="cb275-6"><a href="GLM.html#cb275-6"></a>zero.model.pred &lt;-<span class="st"> </span><span class="kw">exp</span>(u)<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(u)) <span class="co"># Predicciones</span></span>
<span id="cb275-7"><a href="GLM.html#cb275-7"></a>parasitos<span class="op">$</span>ceros &lt;-<span class="st"> </span><span class="kw">ifelse</span>(parasitos<span class="op">$</span>Intensity <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># Ceros vs no ceros</span></span>
<span id="cb275-8"><a href="GLM.html#cb275-8"></a><span class="kw">plot</span>(parasitos<span class="op">$</span>Depth, parasitos<span class="op">$</span>ceros, <span class="dt">pch =</span> <span class="dv">19</span>, <span class="dt">xlab =</span> <span class="st">&quot;Profundidad&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Probabilidad de obtener un cero&quot;</span>)</span>
<span id="cb275-9"><a href="GLM.html#cb275-9"></a><span class="kw">lines</span>(Depth, zero.model.pred, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="fl">2.5</span>, <span class="dt">main =</span> <span class="st">&quot;ZANB&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graficos%20ZANB-1.png" width="672" /></p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="GLM.html#cb276-1"></a><span class="co"># Proceso de conteo</span></span>
<span id="cb276-2"><a href="GLM.html#cb276-2"></a>count.model.coef &lt;-<span class="st"> </span>ZANB<span class="op">$</span>coefficients<span class="op">$</span>count <span class="co"># Coeficientes</span></span>
<span id="cb276-3"><a href="GLM.html#cb276-3"></a>u &lt;-<span class="st"> </span>count.model.coef[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>Depth<span class="op">*</span>count.model.coef[<span class="dv">2</span>]</span>
<span id="cb276-4"><a href="GLM.html#cb276-4"></a>count.model.pred &lt;-<span class="st"> </span><span class="kw">exp</span>(u) <span class="co"># Predicciones</span></span>
<span id="cb276-5"><a href="GLM.html#cb276-5"></a><span class="kw">plot</span>(parasitos<span class="op">$</span>Depth, parasitos<span class="op">$</span>Intensity, <span class="dt">pch =</span> <span class="dv">19</span>, <span class="dt">xlab =</span> <span class="st">&quot;Profundidad&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Prevalencia&quot;</span>)</span>
<span id="cb276-6"><a href="GLM.html#cb276-6"></a><span class="kw">lines</span>(Depth, count.model.pred, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graficos%20ZANB-2.png" width="672" /></p>
</div>
<div id="glms-de-mezcla-zip-y-zinb" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.2.5</span> GLMs de mezcla (ZIP y ZINB)<a href="GLM.html#glms-de-mezcla-zip-y-zinb" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="GLM.html#cb277-1"></a><span class="kw">library</span>(pscl)</span>
<span id="cb277-2"><a href="GLM.html#cb277-2"></a><span class="co"># La primera parte de la fórmula contiene las covariables para el proceso de conteo, la segunda parte contiene las covariables para la probabilidad de los falsos ceros.</span></span>
<span id="cb277-3"><a href="GLM.html#cb277-3"></a>ZIP &lt;-<span class="st"> </span><span class="kw">zeroinfl</span>(Intensity <span class="op">~</span><span class="st"> </span>Depth <span class="op">|</span><span class="st"> </span>Length <span class="op">+</span><span class="st"> </span>Depth, <span class="dt">dist =</span> <span class="st">&quot;poisson&quot;</span>, </span>
<span id="cb277-4"><a href="GLM.html#cb277-4"></a><span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>, <span class="dt">data =</span> parasitos)</span>
<span id="cb277-5"><a href="GLM.html#cb277-5"></a><span class="kw">summary</span>(ZIP)</span></code></pre></div>
<pre><code>## 
## Call:
## zeroinfl(formula = Intensity ~ Depth | Length + Depth, data = parasitos, 
##     dist = &quot;poisson&quot;, link = &quot;logit&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -1.3420 -0.8995 -0.6450 -0.2622 32.6703 
## 
## Count model coefficients (poisson with log link):
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) 1.7740079  0.0412533   43.00   &lt;2e-16 ***
## Depth       0.0041351  0.0001857   22.27   &lt;2e-16 ***
## 
## Zero-inflation model coefficients (binomial with logit link):
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.6523797  0.2870373   5.757 8.58e-09 ***
## Length      -0.0039426  0.0042167  -0.935     0.35    
## Depth       -0.0070509  0.0008585  -8.213  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Number of iterations in BFGS optimization: 1 
## Log-likelihood: -8542 on 5 Df</code></pre>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="GLM.html#cb279-1"></a>ZINB &lt;-<span class="st"> </span><span class="kw">zeroinfl</span>(Intensity <span class="op">~</span><span class="st"> </span>Depth <span class="op">|</span><span class="st"> </span>Length <span class="op">+</span><span class="st"> </span>Depth, <span class="dt">dist =</span> <span class="st">&quot;negbin&quot;</span>, </span>
<span id="cb279-2"><a href="GLM.html#cb279-2"></a><span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>, <span class="dt">data =</span> parasitos)</span>
<span id="cb279-3"><a href="GLM.html#cb279-3"></a><span class="kw">summary</span>(ZINB)</span></code></pre></div>
<pre><code>## 
## Call:
## zeroinfl(formula = Intensity ~ Depth | Length + Depth, data = parasitos, 
##     dist = &quot;negbin&quot;, link = &quot;logit&quot;)
## 
## Pearson residuals:
##      Min       1Q   Median       3Q      Max 
## -0.45165 -0.44692 -0.33559 -0.07448 15.18154 
## 
## Count model coefficients (negbin with log link):
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.868040   0.252504   3.438 0.000587 ***
## Depth        0.005512   0.001216   4.534  5.8e-06 ***
## Log(theta)  -1.572514   0.058398 -26.927  &lt; 2e-16 ***
## 
## Zero-inflation model coefficients (binomial with logit link):
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  6.25506    1.36666   4.577 4.72e-06 ***
## Length       0.03373    0.02168   1.556     0.12    
## Depth       -0.08659    0.01519  -5.699 1.21e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta = 0.2075 
## Number of iterations in BFGS optimization: 26 
## Log-likelihood: -2537 on 6 Df</code></pre>
</div>
<div id="comparacion-de-zip-y-zinb" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.2.6</span> Comparacion de ZIP y ZINB<a href="GLM.html#comparacion-de-zip-y-zinb" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="GLM.html#cb281-1"></a><span class="kw">library</span>(lmtest)</span>
<span id="cb281-2"><a href="GLM.html#cb281-2"></a><span class="kw">lrtest</span>(ZIP, ZINB) <span class="co"># Test de razón de verosimilitud</span></span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: Intensity ~ Depth | Length + Depth
## Model 2: Intensity ~ Depth | Length + Depth
##   #Df  LogLik Df Chisq Pr(&gt;Chisq)    
## 1   5 -8542.3                        
## 2   6 -2537.5  1 12010  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="validación-1" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.6.2.7</span> Validación<a href="GLM.html#validación-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="GLM.html#cb283-1"></a>resid &lt;-<span class="st"> </span><span class="kw">residuals</span>(ZINB, <span class="dt">type =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb283-2"><a href="GLM.html#cb283-2"></a><span class="kw">plot</span>(resid, <span class="kw">predict</span>(ZINB), <span class="dt">xlab =</span> <span class="st">&quot;Residuos&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Predichos&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/validacion%20ZINB-1.png" width="672" /></p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="GLM.html#cb284-1"></a><span class="kw">AIC</span>(ZIP, ZINB)</span></code></pre></div>
<pre><code>##      df       AIC
## ZIP   5 17094.549
## ZINB  6  5086.954</code></pre>
</div>
</div>
<div id="interpretación-y-gráficos-del-modelo-1" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.6.3</span> Interpretación y gráficos del modelo<a href="GLM.html#interpretación-y-gráficos-del-modelo-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="GLM.html#cb286-1"></a><span class="co"># Proceso de falsos ceros</span></span>
<span id="cb286-2"><a href="GLM.html#cb286-2"></a>Depth &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">min</span>(parasitos<span class="op">$</span>Depth), <span class="kw">max</span>(parasitos<span class="op">$</span>Depth), <span class="dt">length =</span> <span class="dv">500</span>)</span>
<span id="cb286-3"><a href="GLM.html#cb286-3"></a>Length &lt;-<span class="st"> </span><span class="kw">mean</span>(parasitos<span class="op">$</span>Length, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb286-4"><a href="GLM.html#cb286-4"></a>zero.model.coef &lt;-<span class="st"> </span>ZINB<span class="op">$</span>coefficients<span class="op">$</span>zero <span class="co"># Coeficientes</span></span>
<span id="cb286-5"><a href="GLM.html#cb286-5"></a>u &lt;-<span class="st"> </span>zero.model.coef[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>Length<span class="op">*</span>zero.model.coef[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>Depth<span class="op">*</span>zero.model.coef[<span class="dv">3</span>]</span>
<span id="cb286-6"><a href="GLM.html#cb286-6"></a>zero.model.pred &lt;-<span class="st"> </span><span class="kw">exp</span>(u)<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(u)) <span class="co"># Predicciones</span></span>
<span id="cb286-7"><a href="GLM.html#cb286-7"></a><span class="kw">plot</span>(Depth, zero.model.pred, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">&quot;Profundidad&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Probabilidad de falso cero&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graficos%20ZINB-1.png" width="672" /></p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="GLM.html#cb287-1"></a><span class="co"># Proceso de conteo</span></span>
<span id="cb287-2"><a href="GLM.html#cb287-2"></a>count.model.coef &lt;-<span class="st"> </span>ZINB<span class="op">$</span>coefficients<span class="op">$</span>count <span class="co"># Coeficientes</span></span>
<span id="cb287-3"><a href="GLM.html#cb287-3"></a>u &lt;-<span class="st"> </span>count.model.coef[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>Depth<span class="op">*</span>count.model.coef[<span class="dv">2</span>]</span>
<span id="cb287-4"><a href="GLM.html#cb287-4"></a>count.model.pred &lt;-<span class="st"> </span><span class="kw">exp</span>(u) <span class="co"># Predicciones</span></span>
<span id="cb287-5"><a href="GLM.html#cb287-5"></a><span class="kw">plot</span>(Depth, count.model.pred, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">&quot;Profundidad&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Numero de parasitos&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graficos%20ZINB-2.png" width="672" /></p>
</div>
</div>
<div id="inferencia-multimodelo" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.7</span> Inferencia multimodelo<a href="GLM.html#inferencia-multimodelo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cabral et al. (2007) estudiaron la distribución de platijas (<em>Solea solea</em>) en el estuario Tagus, Portugal (<code>Solea.txt</code>). Se desea saber qué factores del agua y sustrato están relacionados con la presencia esta especie.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="GLM.html#cb288-1"></a><span class="co"># Análisis exploratorio</span></span>
<span id="cb288-2"><a href="GLM.html#cb288-2"></a>datos &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;Solea.txt&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)</span>
<span id="cb288-3"><a href="GLM.html#cb288-3"></a><span class="kw">str</span>(datos)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    65 obs. of  13 variables:
##  $ Sample       : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ season       : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ month        : int  5 5 5 5 5 5 5 5 5 5 ...
##  $ Area         : int  2 2 2 4 4 4 3 3 3 1 ...
##  $ depth        : num  3 2.6 2.6 2.1 3.2 3.5 1.6 1.7 1.8 4.5 ...
##  $ temperature  : int  20 18 19 20 20 20 19 17 19 21 ...
##  $ salinity     : int  30 29 30 29 30 32 29 28 29 12 ...
##  $ transparency : int  15 15 15 15 15 7 15 10 10 35 ...
##  $ gravel       : num  3.74 1.94 2.88 11.06 9.87 ...
##  $ large_sand   : num  13.15 4.99 8.98 11.96 28.6 ...
##  $ med_fine_sand: num  11.93 5.43 16.85 21.95 19.49 ...
##  $ mud          : num  71.2 87.6 71.3 55 42 ...
##  $ Solea_solea  : int  0 0 1 0 0 0 1 1 0 1 ...</code></pre>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="GLM.html#cb290-1"></a><span class="kw">round</span>(<span class="kw">cor</span>(datos[, <span class="dv">4</span><span class="op">:</span><span class="dv">12</span>]), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                Area depth temperature salinity transparency gravel large_sand
## Area           1.00 -0.55       -0.18     0.76        -0.56   0.44      -0.44
## depth         -0.55  1.00        0.14    -0.66         0.57  -0.24       0.31
## temperature   -0.18  0.14        1.00    -0.35         0.54  -0.16       0.12
## salinity       0.76 -0.66       -0.35     1.00        -0.66   0.38      -0.54
## transparency  -0.56  0.57        0.54    -0.66         1.00  -0.25       0.37
## gravel         0.44 -0.24       -0.16     0.38        -0.25   1.00       0.01
## large_sand    -0.44  0.31        0.12    -0.54         0.37   0.01       1.00
## med_fine_sand -0.69  0.67        0.25    -0.80         0.69  -0.32       0.56
## mud            0.49 -0.47       -0.16     0.63        -0.52  -0.19      -0.87
##               med_fine_sand   mud
## Area                  -0.69  0.49
## depth                  0.67 -0.47
## temperature            0.25 -0.16
## salinity              -0.80  0.63
## transparency           0.69 -0.52
## gravel                -0.32 -0.19
## large_sand             0.56 -0.87
## med_fine_sand          1.00 -0.78
## mud                   -0.78  1.00</code></pre>
<div id="modelos-candidatos" class="section level4 hasAnchor">
<h4><span class="header-section-number">2.7.0.1</span> Modelos candidatos<a href="GLM.html#modelos-candidatos" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="GLM.html#cb292-1"></a><span class="co"># modelo nulo</span></span>
<span id="cb292-2"><a href="GLM.html#cb292-2"></a>m1 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-3"><a href="GLM.html#cb292-3"></a><span class="co"># modelo de temperatura</span></span>
<span id="cb292-4"><a href="GLM.html#cb292-4"></a>m2 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-5"><a href="GLM.html#cb292-5"></a><span class="co"># modelo de salinidad</span></span>
<span id="cb292-6"><a href="GLM.html#cb292-6"></a>m3 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>salinity, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-7"><a href="GLM.html#cb292-7"></a><span class="co"># modelo de transparencia</span></span>
<span id="cb292-8"><a href="GLM.html#cb292-8"></a>m4 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>transparency, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-9"><a href="GLM.html#cb292-9"></a><span class="co"># modelo de profundidad</span></span>
<span id="cb292-10"><a href="GLM.html#cb292-10"></a>m5 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>depth, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-11"><a href="GLM.html#cb292-11"></a><span class="co"># modelo caracteristicas del agua</span></span>
<span id="cb292-12"><a href="GLM.html#cb292-12"></a>m6 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>temperature <span class="op">+</span><span class="st"> </span>salinity <span class="op">+</span><span class="st"> </span>transparency, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-13"><a href="GLM.html#cb292-13"></a><span class="co"># Modelo ubicacion en el espacio</span></span>
<span id="cb292-14"><a href="GLM.html#cb292-14"></a>m7 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>Area <span class="op">+</span><span class="st"> </span>depth <span class="op">+</span><span class="st"> </span>Area<span class="op">:</span>depth, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-15"><a href="GLM.html#cb292-15"></a><span class="co"># Modelo de caracteristicas del sutrato</span></span>
<span id="cb292-16"><a href="GLM.html#cb292-16"></a>m8 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>gravel <span class="op">+</span><span class="st"> </span>large_sand <span class="op">+</span><span class="st"> </span>med_fine_sand, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-17"><a href="GLM.html#cb292-17"></a><span class="co"># Modelo de caracteristicas del sustrato grueso</span></span>
<span id="cb292-18"><a href="GLM.html#cb292-18"></a>m9 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>gravel <span class="op">+</span><span class="st"> </span>large_sand, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-19"><a href="GLM.html#cb292-19"></a><span class="co"># Modelo de caracteristicas del sustrato fino</span></span>
<span id="cb292-20"><a href="GLM.html#cb292-20"></a>m10 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>med_fine_sand, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span>
<span id="cb292-21"><a href="GLM.html#cb292-21"></a><span class="co"># Modelo de profundidad y sustrato</span></span>
<span id="cb292-22"><a href="GLM.html#cb292-22"></a>m11 &lt;-<span class="st"> </span><span class="kw">glm</span>(Solea_solea <span class="op">~</span><span class="st"> </span>depth <span class="op">+</span><span class="st"> </span>gravel <span class="op">+</span><span class="st"> </span>large_sand <span class="op">+</span><span class="st"> </span>med_fine_sand, <span class="dt">family =</span> binomial, <span class="dt">data =</span> datos)</span></code></pre></div>
</div>
<div id="selección-de-modelos" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.7.1</span> Selección de modelos<a href="GLM.html#selección-de-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="GLM.html#cb293-1"></a><span class="kw">library</span>(MuMIn)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MuMIn&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:VGAM&#39;:
## 
##     AICc</code></pre>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="GLM.html#cb296-1"></a>modelos &lt;-<span class="st"> </span><span class="kw">list</span>(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11)</span>
<span id="cb296-2"><a href="GLM.html#cb296-2"></a>ranking.modelos &lt;-<span class="st"> </span><span class="kw">model.sel</span>(modelos, <span class="dt">rank =</span> <span class="st">&quot;AICc&quot;</span>)</span>
<span id="cb296-3"><a href="GLM.html#cb296-3"></a>ranking.modelos</span></code></pre></div>
<pre><code>## Model selection table 
##      (Int)     tmp     sln       trn    dpt    Are Are:dpt       grv lrg_snd
## 7  -1.4470                           1.0730 0.5759 -0.6021                  
## 3   2.6610         -0.1299                                                  
## 6   5.2220 -0.1005 -0.1427 -0.001162                                        
## 5  -2.3250                           0.6152                                 
## 10 -1.5180                                                                  
## 11 -3.0370                           0.5575                 0.008671 0.04312
## 4  -1.5410                  0.043430                                        
## 8  -1.9980                                                  0.011060 0.03151
## 9  -1.3880                                                 -0.014340 0.05502
## 1  -0.4055                                                                  
## 2  -2.6330  0.1006                                                          
##    med_fin_snd          family df  logLik AICc delta weight
## 7              binomial(logit)  4 -31.977 72.6  0.00  0.474
## 3              binomial(logit)  2 -34.280 72.8  0.13  0.444
## 6              binomial(logit)  4 -33.987 76.6  4.02  0.064
## 5              binomial(logit)  2 -38.071 80.3  7.72  0.010
## 10    0.052640 binomial(logit)  2 -39.388 83.0 10.35  0.003
## 11   -0.001628 binomial(logit)  5 -36.156 83.3 10.71  0.002
## 4              binomial(logit)  2 -40.002 84.2 11.58  0.001
## 8     0.041010 binomial(logit)  4 -38.381 85.4 12.81  0.001
## 9              binomial(logit)  3 -39.864 86.1 13.50  0.001
## 1              binomial(logit)  1 -43.746 89.6 16.93  0.000
## 2              binomial(logit)  2 -43.316 90.8 18.20  0.000
## Models ranked by AICc(x)</code></pre>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="GLM.html#cb298-1"></a><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(modelos), ranking.modelos<span class="op">$</span>delta, <span class="dt">pch =</span> <span class="dv">19</span>, <span class="dt">xlab =</span> <span class="st">&quot;Modelo&quot;</span>, <span class="dt">ylab =</span> <span class="kw">expression</span>(Delta <span class="op">~</span><span class="st"> &quot;AICc&quot;</span>))</span>
<span id="cb298-2"><a href="GLM.html#cb298-2"></a><span class="kw">abline</span>(<span class="dt">a =</span> <span class="dv">2</span>, <span class="dt">b =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/seleccion%20modelos-1.png" width="672" /></p>
</div>
<div id="promediado-de-modelos" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.7.2</span> Promediado de modelos<a href="GLM.html#promediado-de-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="GLM.html#cb299-1"></a>modelo.promedio &lt;-<span class="st"> </span><span class="kw">model.avg</span>(ranking.modelos, <span class="dt">subset =</span> delta <span class="op">&lt;</span><span class="st"> </span><span class="dv">2</span>)</span>
<span id="cb299-2"><a href="GLM.html#cb299-2"></a><span class="kw">summary</span>(modelo.promedio)</span></code></pre></div>
<pre><code>## 
## Call:
## model.avg(object = ranking.modelos, subset = delta &lt; 2)
## 
## Component model call: 
## glm(formula = &lt;2 unique values&gt;, family = binomial, data = datos)
## 
## Component models: 
##     df logLik  AICc delta weight
## 234  4 -31.98 72.62  0.00   0.52
## 1    2 -34.28 72.75  0.13   0.48
## 
## Term codes: 
##   salinity      depth       Area Area:depth 
##          1          2          3          4 
## 
## Model-averaged coefficients:  
## (full average) 
##             Estimate Std. Error Adjusted SE z value Pr(&gt;|z|)
## (Intercept)  0.53879    2.60505     2.62506   0.205    0.837
## Area         0.29744    0.75111     0.76410   0.389    0.697
## depth        0.55409    0.68398     0.68935   0.804    0.422
## Area:depth  -0.31101    0.41353     0.41749   0.745    0.456
## salinity    -0.06278    0.06929     0.06946   0.904    0.366
##  
## (conditional average) 
##             Estimate Std. Error Adjusted SE z value Pr(&gt;|z|)    
## (Intercept)  0.53879    2.60505     2.62506   0.205 0.837378    
## Area         0.57586    0.96536     0.98489   0.585 0.558752    
## depth        1.07273    0.59108     0.60304   1.779 0.075260 .  
## Area:depth  -0.60213    0.39469     0.40268   1.495 0.134837    
## salinity    -0.12985    0.03494     0.03562   3.645 0.000267 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="GLM.html#cb301-1"></a><span class="kw">sw</span>(modelo.promedio)</span></code></pre></div>
<pre><code>##                      depth Area Area:depth salinity
## Sum of weights:      0.52  0.52 0.52       0.48    
## N containing models:    1     1    1          1</code></pre>
</div>
<div id="gráfico-del-modelo-promedio" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.7.3</span> Gráfico del modelo promedio<a href="GLM.html#gráfico-del-modelo-promedio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="GLM.html#cb303-1"></a>model.coeff &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">estimate =</span> modelo.promedio<span class="op">$</span>coefficients[<span class="dv">1</span>,])</span>
<span id="cb303-2"><a href="GLM.html#cb303-2"></a>CI &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">confint</span>(modelo.promedio, <span class="dt">full =</span> <span class="ot">TRUE</span>))</span>
<span id="cb303-3"><a href="GLM.html#cb303-3"></a>model.coeff<span class="op">$</span>CI.min &lt;-<span class="st"> </span>CI<span class="op">$</span><span class="st">`</span><span class="dt">2.5 %</span><span class="st">`</span></span>
<span id="cb303-4"><a href="GLM.html#cb303-4"></a>model.coeff<span class="op">$</span>CI.max &lt;-<span class="st"> </span>CI<span class="op">$</span><span class="st">`</span><span class="dt">97.5 %</span><span class="st">`</span></span>
<span id="cb303-5"><a href="GLM.html#cb303-5"></a>model.coeff<span class="op">$</span>coef &lt;-<span class="st"> </span><span class="kw">rownames</span>(model.coeff)</span>
<span id="cb303-6"><a href="GLM.html#cb303-6"></a></span>
<span id="cb303-7"><a href="GLM.html#cb303-7"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb303-8"><a href="GLM.html#cb303-8"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> model.coeff[<span class="dv">2</span><span class="op">:</span><span class="dv">5</span>, ], <span class="kw">aes</span>(<span class="dt">x =</span> coef, <span class="dt">y =</span> estimate)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb303-9"><a href="GLM.html#cb303-9"></a><span class="st">  </span><span class="kw">theme_classic</span>(<span class="dt">base_size =</span> <span class="dv">20</span>) <span class="op">+</span></span>
<span id="cb303-10"><a href="GLM.html#cb303-10"></a><span class="st">  </span><span class="kw">geom_pointrange</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> CI.min, <span class="dt">ymax =</span> CI.max), <span class="dt">size =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;coral&quot;</span>) <span class="op">+</span></span>
<span id="cb303-11"><a href="GLM.html#cb303-11"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Predictor&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Estimado&quot;</span>) <span class="op">+</span></span>
<span id="cb303-12"><a href="GLM.html#cb303-12"></a><span class="st">        </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;gray&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
</div>
<div id="actividades-2" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.8</span> Actividades<a href="GLM.html#actividades-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="ejercicio-3.1" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.8.1</span> Ejercicio 3.1<a href="GLM.html#ejercicio-3.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los datos del archivo <code>gala.xls</code> corresponden a un estudio donde se relevó la diversidad de especies de tortugas de las Islas Galápagos. De cada isla se obtuvo la riqueza de especies (<code>Species</code>), el área (<code>Area</code>), la altitud (<code>Elevation</code>), la distancia a la isla más cercana (<code>Nearest</code>), la distancia a la isla Santa Cruz (<code>Scruz</code>) y el área de la isla más cercana (<code>Adjacent</code>).</p>
<ul>
<li><p>Construya un modelo adecuado que relacione el número de especies endémicas (<code>Endemics</code>) con las variables medidas y analice su poder explicativo.</p></li>
<li><p>Realice uno o más gráficos que representen el modelo ajustado.</p></li>
<li><p>Debido a disponibilidad presupuestaria, sólo se podrán concentrar esfuerzos de conservación en islas con un alto número de especies endémicas (&gt;80). ¿A partir de qué valor de elevación el modelo predice más de 25 especies endémicas? Para esto considere valores constantes en el resto de las covariables incluidas en su modelo.</p></li>
</ul>
</div>
<div id="ejercicio-3.2" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.8.2</span> Ejercicio 3.2<a href="GLM.html#ejercicio-3.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Radim et al. (2015) analizaron la ocurrencia de muérdagos (<em>Loranthus europaeus</em>) en robles de República Checa, teniendo en cuenta el área basal (<code>basal_area</code>), el número de tallos (<code>Number_of_stems</code>), el área basal promedio de los tallos (<code>mean_stem_basal_area</code>), la competencia con árboles infectados basada en el índice de Hegyi (<code>CI_stem</code>) y el rango de los multicaules en ciertas direcciones (<code>Xrange</code>, <code>Yrange</code> y <code>RangeAvg</code>) (<a href="https://doi.org/10.1371/journal.pone.0127055" class="uri">https://doi.org/10.1371/journal.pone.0127055</a>). El conjunto de datos corresponde al archivo <code>Matula_mistletoes_csv</code>.</p>
<ul>
<li><p>Encontrar un modelo que mejor explique la probabilidad de infección por muérdagos (<code>infected</code>) en robles.</p></li>
<li><p>Construya una o más tablas que muestren los resultados principales.</p></li>
<li><p>Realice uno o más gráficos que represente el modelo ajustado.</p></li>
</ul>
</div>
<div id="ejercicio-3.3" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.8.3</span> Ejercicio 3.3<a href="GLM.html#ejercicio-3.3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Tomando como base el conjunto de datos <code>parasitos.txt</code> y el modelo ZAP (de dos partes o “valla”) ajustado, ajuste un modelo ZAP con los mismos predictores pero de forma manual. Para esto, considere utilizar dos GLMs por separado: uno para la probabilidad de obtener un cero, y otro para la distribución de los conteos. Compare los resultados con el modelo obtenido con la función <code>hurdle</code> (paquete <code>pscl</code>).</p>
</div>
<div id="ejercicio-3.4" class="section level3 hasAnchor">
<h3><span class="header-section-number">2.8.4</span> Ejercicio 3.4<a href="GLM.html#ejercicio-3.4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Raventos et al. (2019) evaluaron la respuesta de rasgos de historia de vida a diferentes variables ambientales (mediante técnicas reconstructivas de otolitos) en varias especies de peces (<a href="https://doi.org/10.1111/1365-2656.13435" class="uri">https://doi.org/10.1111/1365-2656.13435</a>). Para esto, se estimaron caracteres de historia de vida, incluyendo la duración larval pelágica (<code>PLD</code>), la tasa de crecimiento (<code>Pre-settlement_growth</code>), el tamaño de asentamiento (<code>Size_of_settlement</code>) y la fecha de puesta (<code>Hatching_day_date</code>). El conjunto de datos se encuentra en el archivo <code>Raventos_etal_2021_JAE_data.txt</code>.</p>
<ul>
<li><p>Analice qué factores determinan la respuesta de las tasas de crecimiento de dos especies considerando la temperatura de la superficie del agua (<code>SST</code>), la clorofila A mensual promedio en mg/m (<code>ChLA</code>) y la estación (<code>Season</code>).</p></li>
<li><p>Compare los predictores de los modelos de cada especie ¿Cuál es más importante para cada una y en qué magnitud?</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="GAM.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
